'use strict';function t(d,e,f,l,p){d.b.ya(d.S,e,f,l,p)}function y(d,e,f,l){d.b.i?t(d,e,f,l):d.b.Ub()._OnMessageFromDOM({type:"event",component:d.S,handler:e,dispatchOpts:l||null,data:f,responseId:null})}function B(d,e,f){d.b.c(d.S,e,f)}function H(d,e){for(const [f,l]of e)B(d,f,l)}window.L=class{constructor(d,e){this.b=d;this.S=e;this.ga=!1;this.xb=()=>this.ab()}Wa(){}ab(){}};
window.Hb=class{constructor(d,e){this.qb=d;this.Mc=e;this.J=-1;this.ja=-Infinity;this.Rc=()=>{this.J=-1;this.ja=Date.now();this.T=!0;this.qb();this.T=!1};this.rb=this.T=!1}};"use strict";function M(d,e){const f=e.elementId,l=d.va(f,e);d.h.set(f,l);l.style.boxSizing="border-box";e.isVisible||(l.style.display="none");e=d.Aa(l);e.addEventListener("focus",()=>{N(d,"elem-focused",f)});e.addEventListener("blur",()=>{N(d,"elem-blurred",f)});d.R&&document.body.appendChild(l)}
function P(d,e,f){B(d,e,l=>{const p=d.h.get(l.elementId);return f(p,l)})}function N(d,e,f,l){l||(l={});l.elementId=f;t(d,e,l)}
window.Ya=class extends self.L{constructor(d,e){super(d,e);this.h=new Map;this.R=!0;H(this,[["create",f=>M(this,f)],["destroy",f=>{{f=f.elementId;const l=this.h.get(f);this.Za(l);this.R&&l.parentElement.removeChild(l);this.h.delete(f)}}],["set-visible",f=>{this.R&&(this.h.get(f.elementId).style.display=f.isVisible?"":"none")}],["update-position",f=>{if(this.R){var l=this.h.get(f.elementId);l.style.left=f.left+"px";l.style.top=f.top+"px";l.style.width=f.width+"px";l.style.height=f.height+"px";f=f.fontSize;
null!==f&&(l.style.fontSize=f+"em")}}],["update-state",f=>{{const l=this.h.get(f.elementId);this.aa(l,f)}}],["focus",f=>this.Ia(f)],["set-css-style",f=>{this.h.get(f.elementId).style[f.prop]=f.val}],["set-attribute",f=>{this.h.get(f.elementId).setAttribute(f.name,f.val)}],["remove-attribute",f=>{this.h.get(f.elementId).removeAttribute(f.name)}]]);P(this,"get-element",f=>f)}va(){throw Error("required override");}Za(){}aa(){throw Error("required override");}Aa(d){return d}Ia(d){const e=this.Aa(this.h.get(d.elementId));
d.focus?e.focus():e.blur()}};"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),e=/android/i.test(navigator.userAgent);let f=0;function l(k){const a=document.createElement("script");a.async=!1;a.type="module";return k.Wc?new Promise(g=>{const h="c3_resolve_"+f;++f;self[h]=g;a.textContent=k.Zc+`\n\nself["${h}"]();`;document.head.appendChild(a)}):new Promise((g,h)=>{a.onload=g;a.onerror=h;a.src=k;document.head.appendChild(a)})}let p=!1,u=!1;function z(){if(!p){try{new Worker("blob://",{get type(){u=
!0}})}catch(k){}p=!0}return u}let v=new Audio;const C={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function O(k){k=await I(k);return(new TextDecoder("utf-8")).decode(k)}
function I(k){return new Promise((a,g)=>{const h=new FileReader;h.onload=m=>a(m.target.result);h.onerror=m=>g(m);h.readAsArrayBuffer(k)})}const A=[];let D=0;window.RealFile=window.File;const E=[],w=new Map,F=new Map;let G=0;const J=[];self.runOnStartup=function(k){if("function"!==typeof k)throw Error("runOnStartup called without a function");J.push(k)};const b=new Set(["cordova","playable-ad","instant-games"]);let c=!1;window.j=class k{constructor(a){this.i=a.ad;this.V=null;this.f="";this.ra=a.Yc;
this.$={};this.Ra=this.yb=null;this.fa=[];this.g=this.Y=null;this.tb=!1;this.U=null;this.H=-1;this.Pc=()=>this.sc();this.G=[];this.a=a.zb;this.ha="file"===location.protocol.substr(0,4);!this.i||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&z()||(this.i=!1);if("playable-ad"===this.a||"instant-games"===this.a)this.i=!1;if("cordova"===this.a&&this.i)if(e){const g=/Chrome\/(\d+)/i.exec(navigator.userAgent);g&&90<=parseInt(g[1],10)||(this.i=!1)}else this.i=!1;this.la=this.m=null;"html5"!==
this.a&&"playable-ad"!==this.a||!this.ha||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.a||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.c("runtime","cordova-fetch-local-file",g=>this.$b(g));this.c("runtime",
"create-job-worker",()=>this.ac());"cordova"===this.a?document.addEventListener("deviceready",()=>this.gb(a)):this.gb(a)}Eb(){return d&&"cordova"===this.a}xa(){const a=navigator.userAgent;return d&&b.has(this.a)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Cb(){return e}$a(){return e&&b.has(this.a)}async gb(a){"macos-wkwebview"===this.a&&this.Ma({type:"ready"});if("playable-ad"===this.a){this.m=self.c3_base64files;this.la={};await this.Ob();for(let h=0,m=a.K.length;h<m;++h){var g=a.K[h].toLowerCase();
this.la.hasOwnProperty(g)?a.K[h]={Wc:!0,Zc:this.la[g]}:this.m.hasOwnProperty(g)&&(a.K[h]=URL.createObjectURL(this.m[g]))}}a.Sc?this.f=a.Sc:(g=location.origin,this.f=("null"===g?"file:///":g)+location.pathname,g=this.f.lastIndexOf("/"),-1!==g&&(this.f=this.f.substr(0,g+1)));a.cd&&(this.$=a.cd);g=new MessageChannel;this.V=g.port1;this.V.onmessage=h=>this._OnMessageFromRuntime(h.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(h=>this.nc(h));this.U=new self.Fb(this);await Q(this.U);
"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.i?await this.Wb(a,g.port2):await this.Vb(a,g.port2)}Ba(a){a=this.$.hasOwnProperty(a)?this.$[a]:a.endsWith("/workermain.js")&&this.$.hasOwnProperty("workermain.js")?this.$["workermain.js"]:"playable-ad"===this.a&&this.m.hasOwnProperty(a.toLowerCase())?this.m[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async wa(a,g,h){if(a.startsWith("blob:"))return new Worker(a,
h);if("cordova"===this.a&&this.ha)return a=await this.ua(h.Vc?a:this.ra+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),h);a=new URL(a,g);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),h)}return new Worker(a,h)}o(){return Math.max(window.innerWidth,1)}l(){return Math.max(window.innerHeight,1)}eb(a){var g=this.U;return{baseUrl:this.f,previewUrl:location.href,
windowInnerWidth:this.o(),windowInnerHeight:this.l(),devicePixelRatio:window.devicePixelRatio,isFullscreen:k.M(),projectData:a.kd,previewImageBlobs:window.cr_previewImageBlobs||this.m,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.hd||"",exportType:a.zb,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.jd,jobScheduler:{inputPort:g.Qa,outputPort:g.Sa,maxNumWorkers:g.Oc},supportedAudioFormats:C,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.ra+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ra+"opus.wasm.wasm",isFileProtocol:this.ha,isiOSCordova:this.Eb(),isiOSWebView:this.xa(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Wb(a,g){var h=this.Ba(a.bd);this.yb=await this.wa(h,this.f,{type:"module",name:"Runtime",Vc:!0});this.g=document.createElement("canvas");this.g.style.display="none";h=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;let m=a.Va||[],
r=a.K;m=await Promise.all(m.map(n=>this.C(n)));r=await Promise.all(r.map(n=>this.C(n)));if("cordova"===this.a)for(let n=0,q=a.ta.length;n<q;++n){const x=a.ta[n],K=x[0];if(K===a.Ua||"scriptsInEvents.js"===K||K.endsWith("/scriptsInEvents.js"))x[1]=await this.C(K)}this.yb.postMessage(Object.assign(this.eb(a),{type:"init-runtime",isInWorker:!0,messagePort:g,canvas:h,workerDependencyScripts:m,engineScripts:r,projectScripts:a.ta,mainProjectScript:a.Ua,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[g,h,...R(this.U)]);this.fa=E.map(n=>new n(this));this.cb();self.c3_callFunction=(n,q)=>this.Y.Xb(n,q);"preview"===this.a&&(self.goToLastErrorScript=()=>this.ya("runtime","go-to-last-error-script"))}async Vb(a,g){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.fa=E.map(n=>new n(this));this.cb();var h=a.K.map(n=>"string"===typeof n?(new URL(n,this.f)).toString():n);Array.isArray(a.Va)&&h.unshift(...a.Va);h=await Promise.all(h.map(n=>
this.C(n)));await Promise.all(h.map(n=>l(n)));h=self.C3_ProjectScriptsStatus;const m=a.Ua,r=a.ta;for(let [n,q]of r)if(q||(q=n),n===m)try{q=await this.C(q),await l(q),"preview"!==this.a||h[n]||this.nb(n,"main script did not run to completion")}catch(x){this.nb(n,x)}else if("scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))q=await this.C(q),await l(q);"preview"===this.a&&"object"!==typeof self.dd.ed?(this.da(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.eb(a),{isInWorker:!1,messagePort:g,canvas:this.g,runOnStartupFunctions:J}),this.ib(),this.Ra=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ra,a))}nb(a,g){this.da();console.error(`[Preview] Failed to load project main script (${a}): `,g);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ib(){this.da()}da(){const a=
window.Tc;a&&(a.parentElement.removeChild(a),window.Tc=null)}async ac(){const a=await S(this.U);return{outputPort:a,transferables:[a]}}Ub(){if(this.i)throw Error("not available in worker mode");return this.Ra}ya(a,g,h,m,r){this.V.postMessage({type:"event",component:a,handler:g,dispatchOpts:m||null,data:h,responseId:null},r)}Gb(a,g){const h=G++,m=new Promise((r,n)=>{F.set(h,{resolve:r,reject:n})});this.V.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:g,responseId:h},
void 0);return m}["_OnMessageFromRuntime"](a){const g=a.type;if("event"===g)return this.fc(a);if("result"===g)this.vc(a);else if("runtime-ready"===g)this.wc();else if("alert-error"===g)this.da(),alert(a.message);else if("creating-runtime"===g)this.ib();else throw Error(`unknown message '${g}'`);}fc(a){const g=a.component,h=a.handler,m=a.data,r=a.responseId;if(a=w.get(g))if(a=a.get(h)){var n=null;try{n=a(m)}catch(q){console.error(`Exception in '${g}' handler '${h}':`,q);null!==r&&this.ca(r,!1,""+q);
return}if(null===r)return n;n&&n.then?n.then(q=>this.ca(r,!0,q)).catch(q=>{console.error(`Rejection from '${g}' handler '${h}':`,q);this.ca(r,!1,""+q)}):this.ca(r,!0,n)}else console.warn(`[DOM] No handler '${h}' for component '${g}'`);else console.warn(`[DOM] No event handlers for component '${g}'`)}ca(a,g,h){let m;h&&h.transferables&&(m=h.transferables);this.V.postMessage({type:"result",responseId:a,isOk:g,result:h},m)}vc(a){const g=a.responseId,h=a.isOk;a=a.result;const m=F.get(g);h?m.resolve(a):
m.reject(a);F.delete(g)}c(a,g,h){let m=w.get(a);m||(m=new Map,w.set(a,m));if(m.has(g))throw Error(`[DOM] Component '${a}' already has handler '${g}'`);m.set(g,h)}static v(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}cb(){for(const a of this.fa)if("runtime"===a.S){this.Y=a;return}throw Error("cannot find runtime DOM handler");}nc(a){this.ya("debugger","message",a)}wc(){for(const a of this.fa)a.Wa()}static M(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||c)}static ea(a){c=!!a}Jb(a){this.G.push(a);this.La()}Hc(a){a=this.G.indexOf(a);if(-1===a)throw Error("invalid callback");this.G.splice(a,1);this.G.length||this.bb()}La(){-1===this.H&&this.G.length&&(this.H=requestAnimationFrame(this.Pc))}bb(){-1!==this.H&&(cancelAnimationFrame(this.H),this.H=-1)}sc(){this.H=-1;for(const a of this.G)a();this.La()}B(a){this.Y.B(a)}A(a){this.Y.A(a)}Ka(){this.Y.Ka()}Ib(){this.tb=!0}Bb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,
5)||"blob:"===a.substr(0,5)}Db(a){return!this.Bb(a)}async C(a){return"cordova"===this.a&&(a.startsWith("file:")||this.ha&&this.Db(a))?(a.startsWith(this.f)&&(a=a.substr(this.f.length)),a=await this.ua(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async $b(a){const g=a.filename;switch(a.as){case "text":return await this.Ab(g);case "buffer":return await this.ua(g);default:throw Error("unsupported type");}}Xa(a){const g=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();
return new Promise((h,m)=>{window.resolveLocalFileSystemURL(g,r=>{r.file(h,m)},m)})}async Ab(a){a=await this.Xa(a);return await O(a)}za(){if(A.length&&!(8<=D)){D++;var a=A.shift();this.Pb(a.filename,a.$c,a.Uc)}}ua(a){return new Promise((g,h)=>{A.push({filename:a,$c:m=>{D--;this.za();g(m)},Uc:m=>{D--;this.za();h(m)}});this.za()})}async Pb(a,g,h){try{const m=await this.Xa(a),r=await I(m);g(r)}catch(m){h(m)}}Ma(a){if("windows-webview2"===this.a)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===
this.a)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Ob(){const a=[];for(const [g,h]of Object.entries(this.m))a.push(this.Nb(g,h));await Promise.all(a)}async Nb(a,g){if("object"===typeof g)this.m[a]=new Blob([g.str],{type:g.type}),this.la[a]=g.str;else{let h=await this.Tb(g);h||(h=this.Qb(g));this.m[a]=h}}async Tb(a){try{return await (await fetch(a)).blob()}catch(g){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
g),null}}Qb(a){a=this.Gc(a);return this.Mb(a.data,a.Xc)}Gc(a){var g=a.indexOf(",");if(0>g)throw new URIError("expected comma in data: uri");var h=a.substring(g+1);g=a.substring(5,g).split(";");a=g[0]||"";const m=g[2];h="base64"===g[1]||"base64"===m?atob(h):decodeURIComponent(h);return{Xc:a,data:h}}Mb(a,g){var h=a.length;let m=h>>2,r=new Uint8Array(h),n=new Uint32Array(r.buffer,0,m),q,x;for(x=q=0;q<m;++q)n[q]=a.charCodeAt(x++)|a.charCodeAt(x++)<<8|a.charCodeAt(x++)<<16|a.charCodeAt(x++)<<24;for(h&=
3;h--;)r[x]=a.charCodeAt(x),++x;return new Blob([r],{type:g})}}}"use strict";
{const d=self.j;function e(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const f=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),l={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},p={dispatchUserScriptEvent:!0},u={dispatchRuntimeEvent:!0};function z(b){return new Promise((c,k)=>{const a=document.createElement("link");a.onload=()=>c(a);a.onerror=g=>k(g);a.rel=
"stylesheet";a.href=b;document.head.appendChild(a)})}function v(b){return new Promise((c,k)=>{const a=new Image;a.onload=()=>c(a);a.onerror=g=>k(g);a.src=b})}async function C(b){b=URL.createObjectURL(b);try{return await v(b)}finally{URL.revokeObjectURL(b)}}function O(b){return new Promise((c,k)=>{let a=new FileReader;a.onload=g=>c(g.target.result);a.onerror=g=>k(g);a.readAsText(b)})}async function I(b,c,k){if(!/firefox/i.test(navigator.userAgent))return await C(b);var a=await O(b);a=(new DOMParser).parseFromString(a,
"image/svg+xml");const g=a.documentElement;if(g.hasAttribute("width")&&g.hasAttribute("height")){const h=g.getAttribute("width"),m=g.getAttribute("height");if(!h.includes("%")&&!m.includes("%"))return await C(b)}g.setAttribute("width",c+"px");g.setAttribute("height",k+"px");a=(new XMLSerializer).serializeToString(a);b=new Blob([a],{type:"image/svg+xml"});return await C(b)}function A(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const D=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function w(b){E.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function F(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await C(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const c=b.getBoundingClientRect();document.body.removeChild(b);return[c.width,
c.height]}};self.C3_RasterSvgImageBlob=async function(b,c,k,a,g){b=await I(b,c,k);const h=document.createElement("canvas");h.width=a;h.height=g;h.getContext("2d").drawImage(b,0,0,c,k);return h};let G=!1;document.addEventListener("pause",()=>G=!0);document.addEventListener("resume",()=>G=!1);function J(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}d.v(class extends self.L{constructor(b){super(b,"runtime");this.ub=!0;this.I=-1;this.Ta="any";this.ob=this.pb=!1;this.u=
null;this.sb="";this.Pa=-1;this.D=this.X=null;this.pa=this.oa=0;this.wb=b.o();this.ka=b.l();this.Z=0;b.c("canvas","update-size",a=>this.Dc(a));b.c("runtime","invoke-download",a=>this.mc(a));b.c("runtime","raster-svg-image",a=>this.tc(a));b.c("runtime","get-svg-image-size",a=>this.jc(a));b.c("runtime","set-target-orientation",a=>this.Bc(a));b.c("runtime","register-sw",()=>this.uc());b.c("runtime","post-to-debugger",a=>this.kb(a));b.c("runtime","go-to-script",a=>this.kb(a));b.c("runtime","before-start-ticking",
()=>this.Zb());b.c("runtime","debug-highlight",a=>this.bc(a));b.c("runtime","enable-device-orientation",()=>this.Lb());b.c("runtime","enable-device-motion",()=>this.Kb());b.c("runtime","add-stylesheet",a=>this.Yb(a));b.c("runtime","alert",a=>this.Da(a));b.c("runtime","hide-cordova-splash",()=>this.kc());b.c("runtime","set-exporting-to-video",a=>this.Jc(a));b.c("runtime","export-to-video-progress",a=>this.hc(a));b.c("runtime","exported-to-video",a=>this.ic(a));const c=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",a=>{const g=a.target;c.has(g.tagName.toLowerCase())||A(g)||a.preventDefault()});const k=b.g;window.addEventListener("selectstart",w);window.addEventListener("gesturehold",w);k.addEventListener("selectstart",w);k.addEventListener("gesturehold",w);window.addEventListener("touchstart",w,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",w,{passive:!1}),k.addEventListener("pointerdown",w)):k.addEventListener("touchstart",w);this.W=
0;window.addEventListener("mousedown",a=>{1===a.button&&a.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.Ec());window.addEventListener("fullscreenchange",()=>this.N());window.addEventListener("webkitfullscreenchange",()=>this.N());window.addEventListener("mozfullscreenchange",()=>this.N());window.addEventListener("fullscreenerror",a=>this.Fa(a));window.addEventListener("webkitfullscreenerror",
a=>this.Fa(a));window.addEventListener("mozfullscreenerror",a=>this.Fa(a));if(b.xa())if(window.visualViewport){let a=Infinity;window.visualViewport.addEventListener("resize",()=>{const g=window.visualViewport.height;g>a&&(document.scrollingElement.scrollTop=0);a=g})}else window.addEventListener("focusout",()=>{{const h=document.activeElement;if(h){var a=h.tagName.toLowerCase();var g=new Set("email number password search tel text url".split(" "));a="textarea"===a?!0:"input"===a?g.has(h.type.toLowerCase()||
"text"):A(h)}else a=!1}a||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=a=>this.Fc(a);this.F=new Set;this.ma=new WeakSet;this.Nc=!1}Zb(){"cordova"===this.b.a?(document.addEventListener("pause",()=>this.Ja(!0)),document.addEventListener("resume",()=>this.Ja(!1))):document.addEventListener("visibilitychange",()=>this.Ja(document.hidden));return{isSuspended:!(!document.hidden&&!G)}}Wa(){window.addEventListener("focus",()=>this.P("window-focus"));window.addEventListener("blur",()=>
{this.P("window-blur",{parentHasFocus:J()});this.W=0});window.addEventListener("focusin",c=>{c=c.target;(D.has(c.tagName.toLowerCase())||A(c))&&this.P("keyboard-blur")});window.addEventListener("keydown",c=>this.jb("keydown",c));window.addEventListener("keyup",c=>this.jb("keyup",c));window.addEventListener("dblclick",c=>this.Ga("dblclick",c,l));window.addEventListener("wheel",c=>this.oc(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this.Ca(c);this.O("pointerdown",
c)}),this.b.i&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.X=new self.Hb(()=>this.Rb(),5),this.X.rb=!0,window.addEventListener("pointerrawupdate",c=>this.rc(c))):window.addEventListener("pointermove",c=>this.O("pointermove",c)),window.addEventListener("pointerup",c=>this.O("pointerup",c)),window.addEventListener("pointercancel",c=>this.O("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.Ca(c);this.Ha("pointerdown",c)}),window.addEventListener("mousemove",
c=>this.Ha("pointermove",c)),window.addEventListener("mouseup",c=>this.Ha("pointerup",c)),window.addEventListener("touchstart",c=>{this.Ca(c);this.ba("pointerdown",c)}),window.addEventListener("touchmove",c=>this.ba("pointermove",c)),window.addEventListener("touchend",c=>this.ba("pointerup",c)),window.addEventListener("touchcancel",c=>this.ba("pointercancel",c)));const b=()=>this.Ka();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.b.Cb()&&!this.b.$a()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Ea(this.l(),navigator.virtualKeyboard.boundingRect.height)}))}Ea(b,c){document.body.style.transform="";if(0<c){var k=document.activeElement;k&&(k=k.getBoundingClientRect(),b=(k.top+k.bottom)/2-(b-c)/2,b>c&&(b=c),0>b&&(b=0),0<b&&(document.body.style.transform=
`translateY(${-b}px)`))}}P(b,c){t(this,b,c||null,u)}o(){return this.b.o()}l(){return this.b.l()}Ec(){const b=this.o(),c=this.l();if(this.b.$a()){if(this.wb===b&&c<this.ka){this.Z=this.ka-c;this.Ea(this.ka,this.Z);return}0<this.Z&&(this.Z=0,this.Ea(c,this.Z));this.wb=b;this.ka=c}this.P("window-resize",{innerWidth:b,innerHeight:c,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.M()});this.b.xa()&&(-1!==this.I&&clearTimeout(this.I),this.lb(b,c,0))}Ic(b,c,k){-1!==this.I&&clearTimeout(this.I);this.I=
setTimeout(()=>this.lb(b,c,k),48)}lb(b,c,k){const a=this.o(),g=this.l();this.I=-1;a!=b||g!=c?this.P("window-resize",{innerWidth:a,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.M()}):10>k&&this.Ic(a,g,k+1)}Bc(b){this.Ta=b.targetOrientation}Kc(){const b=this.Ta;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(b):screen.webkitLockOrientation?
c=screen.webkitLockOrientation(b):screen.mozLockOrientation?c=screen.mozLockOrientation(b):screen.msLockOrientation&&(c=screen.msLockOrientation(b));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",c)}}N(){const b=d.M();b&&"any"!==this.Ta&&this.Kc();t(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.o(),innerHeight:this.l()})}Fa(b){console.warn("[Construct 3] Fullscreen request failed: ",b);t(this,"fullscreenerror",
{isFullscreen:d.M(),innerWidth:this.o(),innerHeight:this.l()})}Ja(b){b?this.b.bb():this.b.La();t(this,"visibilitychange",{hidden:b})}jb(b,c){"Backspace"===c.key&&w(c);const k=f.get(c.code)||c.code;y(this,b,{code:k,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},l)}oc(b){t(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,
timeStamp:b.timeStamp},l)}Ga(b,c,k){e(c)||y(this,b,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},k)}Ha(b,c){if(!e(c)){var k=this.W;"pointerdown"===b&&0!==k?b="pointermove":"pointerup"===b&&0!==c.buttons&&(b="pointermove");y(this,b,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:k,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,
movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},l);this.W=c.buttons;this.Ga(c.type,c,p)}}O(b,c){if(this.X&&"pointermove"!==b){var k=this.X;k.T||(-1!==k.J&&(self.clearTimeout(k.J),k.J=-1),k.ja=Date.now())}k=0;"mouse"===c.pointerType&&(k=this.W);y(this,b,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:k,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,
movementX:(c.movementX||0)+this.oa,movementY:(c.movementY||0)+this.pa,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},l);this.pa=this.oa=0;"mouse"===c.pointerType&&(k="mousemove","pointerdown"===b?k="mousedown":"pointerup"===b&&(k="mouseup"),this.Ga(k,c,p),this.W=c.buttons)}rc(b){this.D&&(this.oa+=this.D.movementX||0,this.pa+=this.D.movementY||0);this.D=b;b=this.X;if(-1===
b.J){var c=Date.now(),k=c-b.ja,a=b.Mc;k>=a&&b.rb?(b.ja=c,b.T=!0,b.qb(),b.T=!1):b.J=self.setTimeout(b.Rc,Math.max(a-k,4))}}Rb(){this.O("pointermove",this.D);this.D=null}ba(b,c){for(let k=0,a=c.changedTouches.length;k<a;++k){const g=c.changedTouches[k];y(this,b,{pointerId:g.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(g.radiusX||g.webkitRadiusX||0),height:2*(g.radiusY||
g.webkitRadiusY||0),pressure:g.force||g.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:g.rotationAngle||0,timeStamp:c.timeStamp},l)}}Ca(b){window!==window.top&&window.focus();this.hb(b.target)&&document.activeElement&&!this.hb(document.activeElement)&&document.activeElement.blur()}hb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}Lb(){this.pb||(this.pb=!0,window.addEventListener("deviceorientation",b=>this.dc(b)),window.addEventListener("deviceorientationabsolute",
b=>this.ec(b)))}Kb(){this.ob||(this.ob=!0,window.addEventListener("devicemotion",b=>this.cc(b)))}dc(b){t(this,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},l)}ec(b){t(this,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},l)}cc(b){let c=null;var k=b.acceleration;k&&(c=
{x:k.x||0,y:k.y||0,z:k.z||0});k=null;var a=b.accelerationIncludingGravity;a&&(k={x:a.x||0,y:a.y||0,z:a.z||0});a=null;const g=b.rotationRate;g&&(a={alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0});t(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:k,rotationRate:a,interval:b.interval,timeStamp:b.timeStamp},l)}Dc(b){var c=this.b;c.tb||(c=c.g,c.style.width=b.styleWidth+"px",c.style.height=b.styleHeight+"px",c.style.marginLeft=b.marginLeft+"px",c.style.marginTop=b.marginTop+"px",this.ub&&
(c.style.display="",this.ub=!1))}mc(b){const c=b.url;b=b.filename;const k=document.createElement("a"),a=document.body;k.textContent=b;k.href=c;k.download=b;a.appendChild(k);k.click();a.removeChild(k)}async tc(b){var c=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);c=c?await createImageBitmap(b,c):await createImageBitmap(b);return{imageBitmap:c,transferables:[c]}}async jc(b){return await self.C3_GetSvgImageSize(b.blob)}async Yb(b){await z(b.url)}Ka(){var b=
[...this.F];this.F.clear();if(!this.Nc)for(const c of b)(b=c.play())&&b.catch(()=>{this.ma.has(c)||this.F.add(c)})}B(b){if("function"!==typeof b.play)throw Error("missing play function");this.ma.delete(b);let c;try{c=b.play()}catch(k){this.F.add(b);return}c&&c.catch(()=>{this.ma.has(b)||this.F.add(b)})}A(b){this.F.delete(b);this.ma.add(b)}kc(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}bc(b){if(b.show){this.u||(this.u=document.createElement("div"),this.u.id=
"inspectOutline",document.body.appendChild(this.u));var c=this.u;c.style.display="";c.style.left=b.left-1+"px";c.style.top=b.top-1+"px";c.style.width=b.width+2+"px";c.style.height=b.height+2+"px";c.textContent=b.name}else this.u&&(this.u.style.display="none")}uc(){window.C3_RegisterSW&&window.C3_RegisterSW()}kb(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}Xb(b,c){return this.b.Gb(this.S,{name:b,params:c})}Da(b){alert(b.message)}Fc(b){"entered-fullscreen"===b?(d.ea(!0),
this.N()):"exited-fullscreen"===b?(d.ea(!1),this.N()):console.warn("Unknown wrapper message: ",b)}Jc(b){const c=document.createElement("h1");c.id="exportToVideoMessage";c.textContent=b.message;document.body.prepend(c);document.body.classList.add("exportingToVideo");this.b.g.style.display="";this.b.Ib()}hc(b){this.sb=b.message;-1===this.Pa&&(this.Pa=setTimeout(()=>this.Sb(),250))}Sb(){this.Pa=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=this.sb)}ic(b){window.gd({type:"exported-video",
blob:b.blob,time:b.time})}})}"use strict";async function Q(d){if(d.Lc)throw Error("already initialised");d.Lc=!0;var e=d.qa.Ba("dispatchworker.js");d.Oa=await d.qa.wa(e,d.f,{name:"DispatchWorker"});e=new MessageChannel;d.Qa=e.port1;d.Oa.postMessage({type:"_init","in-port":e.port2},[e.port2]);d.Sa=await S(d)}function R(d){return[d.Qa,d.Sa]}
async function S(d){const e=d.vb.length;var f=d.qa.Ba("jobworker.js");f=await d.qa.wa(f,d.f,{name:"JobWorker"+e});const l=new MessageChannel,p=new MessageChannel;d.Oa.postMessage({type:"_addJobWorker",port:l.port1},[l.port1]);f.postMessage({type:"init",number:e,"dispatch-port":l.port2,"output-port":p.port2},[l.port2,p.port2]);d.vb.push(f);return p.port1}
self.Fb=class{constructor(d){this.qa=d;this.f=d.f;this.f="preview"===d.a?this.f+"workers/":this.f+d.ra;this.Oc=Math.min(navigator.hardwareConcurrency||2,16);this.Oa=null;this.vb=[];this.Sa=this.Qa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.j({ad:!0,bd:"workermain.js",K:["scripts/c3runtime.js"],ta:[],Ua:"",Yc:"scripts/",Va:[],zb:"html5"}));"use strict";
{function d(e){e.stopPropagation()}self.j.v(class extends self.Ya{constructor(e){super(e,"button")}va(e,f){const l=document.createElement("input");var p=l;f.isCheckbox?(l.type="checkbox",p=document.createElement("label"),p.appendChild(l),p.appendChild(document.createTextNode("")),p.style.fontFamily="sans-serif",p.style.userSelect="none",p.style.webkitUserSelect="none",p.style.display="inline-block",p.style.color="black"):l.type="button";p.style.position="absolute";p.addEventListener("touchstart",
d);p.addEventListener("touchmove",d);p.addEventListener("touchend",d);p.addEventListener("mousedown",d);p.addEventListener("mouseup",d);p.addEventListener("keydown",d);p.addEventListener("keyup",d);l.addEventListener("click",()=>{var u={isChecked:l.checked};u.elementId=e;y(this,"click",u)});f.id&&(l.id=f.id);this.aa(p,f);return p}fb(e){return"input"===e.tagName.toLowerCase()?e:e.firstChild}Aa(e){return this.fb(e)}aa(e,f){const l=this.fb(e);l.checked=f.isChecked;l.disabled=!f.isEnabled;e.title=f.title;
e===l?l.value=f.text:e.lastChild.textContent=f.text}})}"use strict";
self.j.v(class extends self.Ya{constructor(d){super(d,"video");this.sa=this.ia=this.R=!1;this.na=this.Qc=0;this.Na=new WeakSet;B(this,"init",e=>this.lc(e));P(this,"play",e=>this.qc(e));P(this,"pause",e=>this.pc(e));P(this,"set-source",(e,f)=>this.Ac(e,f));P(this,"set-playback-time",(e,f)=>this.zc(e,f));P(this,"set-looping",(e,f)=>this.xc(e,f));P(this,"set-muted",(e,f)=>this.yc(e,f));P(this,"set-volume",(e,f)=>this.Cc(e,f));self.C3Video_GetElement=e=>this.h.get(e)}async lc(d){this.ia=d.isInWorker;
d=document.createElement("video");this.sa=!!d.requestVideoFrameCallback;return{"video/webm":!!d.canPlayType("video/webm"),"video/ogg":!!d.canPlayType("video/ogg"),"video/mp4":!!d.canPlayType("video/mp4")}}B(d){this.b.B(d);this.ia&&this.sa&&-1===d.c3_rvfcId&&(d.c3_rvfcId=d.requestVideoFrameCallback(()=>this.mb(d)))}A(d){this.b.A(d);this.ia&&this.sa&&-1!==d.c3_rvfcId&&(d.cancelVideoFrameCallback(d.c3_rvfcId),d.c3_rvfcId=-1)}async mb(d){if(!this.Na.has(d)){d.c3_rvfcId=d.requestVideoFrameCallback(()=>
this.mb(d));try{const e=d.c3_sequenceNumber++,f=await createImageBitmap(d);e>d.c3_lastFrameSequence&&(d.c3_imageBitmap=f,d.c3_lastFrameSequence=e)}catch(e){}}}va(d,e){const f=document.createElement("video");f.crossOrigin="anonymous";f.playsInline=!0;f.c3_imageBitmap=null;f.c3_rvfcId=-1;f.c3_sequenceNumber=0;f.c3_lastFrameSequence=-1;f.addEventListener("canplay",()=>this.s(f,d,0));f.addEventListener("canplaythrough",()=>this.s(f,d,1));f.addEventListener("ended",()=>this.s(f,d,2));f.addEventListener("error",
()=>this.s(f,d,3));f.addEventListener("loadstart",()=>this.s(f,d,4));f.addEventListener("playing",()=>this.s(f,d,5));f.addEventListener("pause",()=>this.s(f,d,6));f.addEventListener("stalled",()=>this.s(f,d,7));const l=e.autoplay;0===l?(f.autoplay=!1,f.preload="none"):1===l?(f.autoplay=!1,f.preload="auto"):f.autoplay=!0;e.src&&(f.src=e.src);2===l&&this.B(f);this.na++;this.ga||(this.b.Jb(this.xb),this.ga=!0);return f}s(d,e,f){this.Na.has(d)||N(this,"playback-event",e,{type:f})}aa(){}Za(d){this.A(d);
d&&!d.paused&&!d.ended&&0<d.currentTime&&d.pause();d.src="";this.na=Math.max(this.na-1,0);0===this.na&&this.ga&&(this.b.Hc(this.xb),this.ga=!1);this.Na.add(d)}qc(d){this.B(d)}pc(d){this.A(d);d.pause()}Ac(d,e){d.src=e.src;d.load()}zc(d,e){try{d.currentTime=e.time}catch(f){console.error("[Video] Exception setting playback time: ",f)}}xc(d,e){d.loop=e.isLooping}yc(d,e){d.muted=e.isMuted}Cc(d,e){d.volume=e.volume}ab(){const d={},e={sequenceNumber:this.Qc++,videoData:d},f=[],l=[];for(const [p,u]of this.h.entries()){const z=
{currentTime:u.currentTime,duration:u.duration,videoWidth:u.videoWidth,videoHeight:u.videoHeight};if(this.ia)if(this.sa){const v=u.c3_imageBitmap;u.c3_imageBitmap=null;(z.imageBitmap=v)&&f.push(v)}else l.push(createImageBitmap(u).then(v=>{z.imageBitmap=v;f.push(v)}).catch(()=>{z.imageBitmap=null}));d[p.toString()]=z}Promise.all(l).then(()=>t(this,"state",e,!1,f))}});"use strict";
self.j.v(class extends self.L{constructor(d){super(d,"mouse");H(this,[["cursor",e=>{document.documentElement.style.cursor=e}],["request-pointer-lock",()=>{this.b.g.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{t(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{t(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function T(d,e){e=e.type;let f=!0;0===e?f=await U():1===e&&(f=await V());t(d,"permission-result",{type:e,result:f})}async function U(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}
async function V(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}self.j.v(class extends self.L{constructor(d){super(d,"touch");B(this,"request-permission",e=>T(this,e))}});"use strict";
function W(d){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(e=>t(d,"sw-message",e.data))}
function X(d){d=d.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(d):screen.webkitLockOrientation?e=screen.webkitLockOrientation(d):screen.mozLockOrientation?e=screen.mozLockOrientation(d):screen.msLockOrientation&&(e=screen.msLockOrientation(d));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",
e)}}
self.j.v(class extends self.L{constructor(d){super(d,"browser");this.a="";H(this,[["get-initial-state",e=>{this.a=e.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>W(this)],
["alert",e=>this.Da(e)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",e=>this.Ia(e)],["vibrate",e=>{navigator.vibrate&&navigator.vibrate(e.pattern)}],["lock-orientation",e=>X(e)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(e){}}],["navigate",e=>{var f=e.type;if("back"===f)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===f)window.history.forward();else if("reload"===f)location.reload();else if("url"===f){f=e.url;const l=e.target;e=e.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):"preview"===
e||"windows-webview2"===e?window.open(f,"_blank"):this.fd||(2===l?window.top.location=f:1===l?window.parent.location=f:window.location=f)}else"new-window"===f&&(f=e.url,e=e.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):window.open(f,e))}],["request-fullscreen",e=>{if("windows-webview2"===this.a||"macos-wkwebview"===this.a)self.j.ea(!0),this.b.Ma({type:"set-fullscreen",fullscreen:!0});else{const f={navigationUI:"auto"};e=e.navUI;1===e?f.navigationUI="hide":
2===e&&(f.navigationUI="show");e=document.documentElement;e.requestFullscreen?e.requestFullscreen(f):e.mozRequestFullScreen?e.mozRequestFullScreen(f):e.msRequestFullscreen?e.msRequestFullscreen(f):e.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):e.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.a||"macos-wkwebview"===this.a?(self.j.ea(!1),this.b.Ma({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",e=>{location.hash=e.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{t(this,"backbutton")})}Da(d){alert(d.message)}Ia(d){d=d.isFocus;if("nwjs"===this.a){const e="nwjs"===this.a?nw.Window.get():null;d?e.focus():e.blur()}else d?window.focus():window.blur()}});
