'use strict';function w(d,a,b,e,g){d.h.Hb(d.hb,a,b,e,g)}function C(d,a,b,e){d.h.ga?w(d,a,b,e):d.h.Mf()._OnMessageFromDOM({type:"event",component:d.hb,handler:a,dispatchOpts:e||null,data:b,responseId:null})}function F(d,a,b){d.h.C(d.hb,a,b)}function K(d,a){for(const [b,e]of a)F(d,b,e)}function L(d){d.Yb||(d.h.wf(d.De),d.Yb=!0)}function M(d){d.Yb&&(d.h.Mg(d.De),d.Yb=!1)}window.Ga=class{constructor(d,a){this.h=d;this.hb=a;this.Yb=!1;this.De=()=>this.Ba()}zd(){}Ba(){}};
function N(d){-1!==d.Va&&(self.clearTimeout(d.Va),d.Va=-1)}window.lf=class{constructor(d,a){this.dd=d;this.nh=a;this.Va=-1;this.Zb=-Infinity;this.Ee=()=>{this.Va=-1;this.Zb=Date.now();this.mb=!0;this.dd();this.mb=!1};this.he=this.mb=!1}f(){N(this);this.Ee=this.dd=null}};"use strict";
function P(d,a){const b=a.elementId,e=d.vc(b,a);d.U.set(b,e);e.style.boxSizing="border-box";a.isVisible||(e.style.display="none");a=d.Mc(e);a.addEventListener("focus",()=>{R(d,"elem-focused",b)});a.addEventListener("blur",()=>{R(d,"elem-blurred",b)});d.fb&&document.body.appendChild(e)}function S(d,a,b){F(d,a,e=>{const g=d.U.get(e.elementId);return b(g,e)})}function R(d,a,b,e){e||(e={});e.elementId=b;w(d,a,e)}
window.Dd=class extends self.Ga{constructor(d,a){super(d,a);this.U=new Map;this.fb=!0;K(this,[["create",b=>P(this,b)],["destroy",b=>{{b=b.elementId;const e=this.U.get(b);this.Fd(e);this.fb&&e.parentElement.removeChild(e);this.U.delete(b)}}],["set-visible",b=>{this.fb&&(this.U.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.fb){var e=this.U.get(b.elementId);e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+"px";e.style.height=b.height+"px";
b=b.fontSize;null!==b&&(e.style.fontSize=b+"em")}}],["update-state",b=>{{const e=this.U.get(b.elementId);this.Mb(e,b)}}],["focus",b=>this.Xc(b)],["set-css-style",b=>{this.U.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.U.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.U.get(b.elementId).removeAttribute(b.name)}]]);S(this,"get-element",b=>b)}vc(){throw Error("required override");}Fd(){}Mb(){throw Error("required override");}Mc(d){return d}Xc(d){const a=
this.Mc(this.U.get(d.elementId));d.focus?a.focus():a.blur()}};"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function e(n){const c=document.createElement("script");c.async=!1;c.type="module";return n.yh?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=n.Dh+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=n;document.head.appendChild(c)})}let g=!1,m=!1;function q(){if(!g){try{new Worker("blob://",{get type(){m=
!0}})}catch(n){}g=!0}return m}let u=new Audio;const B={"audio/webm; codecs=opus":!!u.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!u.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!u.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!u.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!u.canPlayType("audio/mp4"),"audio/mpeg":!!u.canPlayType("audio/mpeg")};u=null;async function G(n){n=await y(n);return(new TextDecoder("utf-8")).decode(n)}
function y(n){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(n)})}const z=[];let D=0;window.RealFile=window.File;const H=[],A=new Map,I=new Map;let J=0;const O=[];self.runOnStartup=function(n){if("function"!==typeof n)throw Error("runOnStartup called without a function");O.push(n)};const f=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.ca=class n{constructor(c){this.ga=c.Fh;this.va=null;this.$="";this.pc=c.Ch;
this.Db={};this.Oa=this.Cb=null;this.Wb=[];this.D=this.Ta=null;this.nd=!1;this.ke=0;this.pb=null;this.Sa=-1;this.sh=()=>this.qg();this.Ra=[];this.u=c.Fe;this.nb="file"===location.protocol.substr(0,4);!this.ga||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.ga=!1);if("playable-ad"===this.u||"instant-games"===this.u)this.ga=!1;if("cordova"===this.u&&this.ga)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ga=!1)}else this.ga=!1;this.bc=
this.ma=null;"html5"!==this.u&&"playable-ad"!==this.u||!this.nb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.u||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",
k=>this.Tf(k));this.C("runtime","create-job-worker",()=>this.Uf());"cordova"===this.u?document.addEventListener("deviceready",()=>this.Td(c)):this.Td(c)}f(){this.Jc();this.va&&(this.va=this.va.onmessage=null);this.Cb&&(this.Cb.terminate(),this.Cb=null);this.Oa&&(this.Oa.f(),this.Oa=null);this.D&&(this.D.parentElement.removeChild(this.D),this.D=null)}ff(){return d&&"cordova"===this.u}Dc(){const c=navigator.userAgent;return d&&f.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}df(){return a}Cc(){return a&&
f.has(this.u)}async Td(c){"macos-wkwebview"===this.u&&this.ad({type:"ready"});if("playable-ad"===this.u){this.ma=self.c3_base64files;this.bc={};await this.Bf();for(let l=0,p=c.Wa.length;l<p;++l){var k=c.Wa[l].toLowerCase();this.bc.hasOwnProperty(k)?c.Wa[l]={yh:!0,Dh:this.bc[k]}:this.ma.hasOwnProperty(k)&&(c.Wa[l]=URL.createObjectURL(this.ma[k]))}}c.Bh?this.$=c.Bh:(k=location.origin,this.$=("null"===k?"file:///":k)+location.pathname,k=this.$.lastIndexOf("/"),-1!==k&&(this.$=this.$.substr(0,k+1)));
c.Hh&&(this.Db=c.Hh);k=new MessageChannel;this.va=k.port1;this.va.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.hg(l));this.pb=new self.gf(this);await T(this.pb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((l,p)=>{window.AndroidFullScreen.immersiveMode(l,p)})}catch(l){console.error("Failed to enter Android immersive mode: ",l)}this.ga?await this.Of(c,
k.port2):await this.Nf(c,k.port2)}Nc(c){c=this.Db.hasOwnProperty(c)?this.Db[c]:c.endsWith("/workermain.js")&&this.Db.hasOwnProperty("workermain.js")?this.Db["workermain.js"]:"playable-ad"===this.u&&this.ma.hasOwnProperty(c.toLowerCase())?this.ma[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async wc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.u&&this.nb)return c=await this.Eb(l.xh?c:this.pc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),
l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}sa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}Rd(c){var k=this.$,l=location.href,p=this.sa(),v=this.ja(),r=window.devicePixelRatio,t=n.Za(),x=c.Oh,E=window.cr_previewImageBlobs||this.ma,X=window.cr_previewProjectFileBlobs,Y=window.cr_previewProjectFiles,Z=window.Mh||
"";c=c.Fe;var aa=(new URLSearchParams(self.location.search)).has("debug"),Q=this.pb;return{runtimeBaseUrl:k,previewUrl:l,windowInnerWidth:p,windowInnerHeight:v,devicePixelRatio:r,isFullscreen:t,projectData:x,previewImageBlobs:E,previewProjectFileBlobs:X,previewProjectFileSWUrls:Y,swClientId:Z,exportType:c,isDebug:aa,ife:!!self.Nh,jobScheduler:{inputPort:Q.md,outputPort:Q.td,maxNumWorkers:Q.ph},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.pc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.pc+"opus.wasm.wasm",isFileProtocol:this.nb,isiOSCordova:this.ff(),isiOSWebView:this.Dc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Of(c,k){var l=this.Nc(c.Gh);this.Cb=await this.wc(l,this.$,{type:"module",name:"Runtime",xh:!0});this.D=document.createElement("canvas");this.D.style.display="none";l=this.D.transferControlToOffscreen();document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let p=c.yd||[],v=c.Wa;
p=await Promise.all(p.map(r=>this.Ia(r)));v=await Promise.all(v.map(r=>this.Ia(r)));if("cordova"===this.u)for(let r=0,t=c.tc.length;r<t;++r){const x=c.tc[r],E=x[0];if(E===c.wd||"scriptsInEvents.js"===E||E.endsWith("/scriptsInEvents.js"))x[1]=await this.Ia(E)}this.Cb.postMessage(Object.assign(this.Rd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:v,projectScripts:c.tc,mainProjectScript:c.wd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,
l,...ba(this.pb)]);this.Wb=H.map(r=>new r(this));this.Qd();self.c3_callFunction=(r,t)=>this.Ta.Pf(r,t);"preview"===this.u&&(self.goToLastErrorScript=()=>this.Hb("runtime","go-to-last-error-script"))}async Nf(c,k){this.D=document.createElement("canvas");this.D.style.display="none";document.body.appendChild(this.D);window.c3canvas=this.D;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wb=H.map(r=>new r(this));this.Qd();var l=c.Wa.map(r=>"string"===typeof r?(new URL(r,this.$)).toString():
r);Array.isArray(c.yd)&&l.unshift(...c.yd);l=await Promise.all(l.map(r=>this.Ia(r)));await Promise.all(l.map(r=>e(r)));l=self.C3_ProjectScriptsStatus;const p=c.wd,v=c.tc;for(let [r,t]of v)if(t||(t=r),r===p)try{t=await this.Ia(t),await e(t),"preview"!==this.u||l[r]||this.ce(r,"main script did not run to completion")}catch(x){this.ce(r,x)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ia(t),await e(t);"preview"===this.u&&"object"!==typeof self.Ih.Jh?(this.Rb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Rd(c),{isInWorker:!1,messagePort:k,canvas:this.D,runOnStartupFunctions:O}),this.Vd(),this.Oa=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Oa,c))}ce(c,k){this.Rb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Vd(){this.Rb()}Rb(){const c=
window.uh;c&&(c.parentElement.removeChild(c),window.uh=null)}async Uf(){const c=await U(this.pb);return{outputPort:c,transferables:[c]}}Mf(){if(this.ga)throw Error("not available in worker mode");return this.Oa}Hb(c,k,l,p,v){this.va.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},v)}Jd(c,k,l,p,v){const r=J++,t=new Promise((x,E)=>{I.set(r,{resolve:x,reject:E})});this.va.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
v);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Zf(c);if("result"===k)this.tg(c);else if("runtime-ready"===k)this.ug();else if("alert-error"===k)this.Rb(),alert(c.message);else if("creating-runtime"===k)this.Vd();else throw Error(`unknown message '${k}'`);}Zf(c){const k=c.component,l=c.handler,p=c.data,v=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==v&&this.Qb(v,!1,""+t);return}if(null===
v)return r;r&&r.then?r.then(t=>this.Qb(v,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Qb(v,!1,""+t)}):this.Qb(v,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Qb(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.va.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}tg(c){const k=c.responseId,l=c.isOk;c=c.result;const p=I.get(k);l?p.resolve(c):p.reject(c);I.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static ya(c){if(H.includes(c))throw Error("DOM handler already added");H.push(c)}Qd(){for(const c of this.Wb)if("runtime"===c.hb){this.Ta=c;return}throw Error("cannot find runtime DOM handler");}hg(c){this.Hb("debugger","message",c)}ug(){for(const c of this.Wb)c.zd()}static Za(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Sb(c){h=!!c}wf(c){this.Ra.push(c);this.$c()}Mg(c){c=this.Ra.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ra.splice(c,1);this.Ra.length||this.Jc()}$c(){-1===this.Sa&&this.Ra.length&&(this.Sa=requestAnimationFrame(this.sh))}Jc(){-1!==this.Sa&&(cancelAnimationFrame(this.Sa),this.Sa=-1)}qg(){this.Sa=-1;for(const c of this.Ra)c();this.$c()}Z(c){this.Ta.Z(c)}ba(c){this.Ta.ba(c)}Zc(){this.Ta.Zc()}Kb(c){this.Ta.Kb(c)}ef(){return!!B["audio/webm; codecs=opus"]}async lh(c){c=await this.Jd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}pf(c){this.nd=!0;this.ke=c}cf(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}Id(c){return!this.cf(c)}async Ia(c){return"cordova"===this.u&&(c.startsWith("file:")||this.nb&&this.Id(c))?(c.startsWith(this.$)&&(c=c.substr(this.$.length)),c=await this.Eb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Tf(c){const k=c.filename;switch(c.as){case "text":return await this.We(k);
case "buffer":return await this.Eb(k);default:throw Error("unsupported type");}}Cd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,v=>{v.file(l,p)},p)})}async We(c){c=await this.Cd(c);return await G(c)}Kc(){if(z.length&&!(8<=D)){D++;var c=z.shift();this.Cf(c.filename,c.Eh,c.wh)}}Eb(c){return new Promise((k,l)=>{z.push({filename:c,Eh:p=>{D--;this.Kc();k(p)},wh:p=>{D--;this.Kc();l(p)}});this.Kc()})}async Cf(c,k,
l){try{const p=await this.Cd(c),v=await y(p);k(v)}catch(p){l(p)}}ad(c){if("windows-webview2"===this.u)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.u)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Bf(){const c=[];for(const [k,l]of Object.entries(this.ma))c.push(this.Af(k,l));await Promise.all(c)}async Af(c,k){if("object"===typeof k)this.ma[c]=new Blob([k.str],{type:k.type}),this.bc[c]=
k.str;else{let l=await this.Kf(k);l||(l=this.Ef(k));this.ma[c]=l}}async Kf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}Ef(c){c=this.Gg(c);return this.zf(c.data,c.zh)}Gg(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);
k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{zh:c,data:l}}zf(c,k){var l=c.length;let p=l>>2,v=new Uint8Array(l),r=new Uint32Array(v.buffer,0,p),t,x;for(x=t=0;t<p;++t)r[t]=c.charCodeAt(x++)|c.charCodeAt(x++)<<8|c.charCodeAt(x++)<<16|c.charCodeAt(x++)<<24;for(l&=3;l--;)v[x]=c.charCodeAt(x),++x;return new Blob([v],{type:k})}}}"use strict";
{const d=self.ca;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),e={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function q(f){return new Promise((h,n)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>n(k);c.rel=
"stylesheet";c.href=f;document.head.appendChild(c)})}function u(f){return new Promise((h,n)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>n(k);c.src=f})}async function B(f){f=URL.createObjectURL(f);try{return await u(f)}finally{URL.revokeObjectURL(f)}}function G(f){return new Promise((h,n)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>n(k);c.readAsText(f)})}async function y(f,h,n){if(!/firefox/i.test(navigator.userAgent))return await B(f);var c=await G(f);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(f)}k.setAttribute("width",h+"px");k.setAttribute("height",n+"px");c=(new XMLSerializer).serializeToString(c);f=new Blob([c],{type:"image/svg+xml"});return await B(f)}function z(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const D=new Set(["input",
"textarea","datalist","select"]),H=new Set(["canvas","body","html"]);function A(f){H.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function I(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await B(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const h=f.getBoundingClientRect();document.body.removeChild(f);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(f,h,n,c,k){f=await y(f,h,n);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(f,0,0,h,n);return l};let J=!1;document.addEventListener("pause",()=>J=!0);document.addEventListener("resume",()=>J=!1);function O(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}d.ya(class extends self.Ga{constructor(f){super(f,"runtime");this.qe=!0;this.Ua=-1;this.ud="any";this.de=this.ee=!1;this.Da=
null;this.X=!1;this.le="";this.hd=-1;this.Na=this.xb=null;this.lc=this.kc=0;this.je=!1;this.ue=f.sa();this.$b=f.ja();this.Ab=0;f.C("canvas","update-size",c=>this.Dg(c));f.C("runtime","invoke-download",c=>this.fg(c));f.C("runtime","raster-svg-image",c=>this.rg(c));f.C("runtime","get-svg-image-size",c=>this.cg(c));f.C("runtime","set-target-orientation",c=>this.Ag(c));f.C("runtime","register-sw",()=>this.sg());f.C("runtime","post-to-debugger",c=>this.Yd(c));f.C("runtime","go-to-script",c=>this.Yd(c));
f.C("runtime","before-start-ticking",()=>this.Sf());f.C("runtime","debug-highlight",c=>this.Vf(c));f.C("runtime","enable-device-orientation",()=>this.yf());f.C("runtime","enable-device-motion",()=>this.xf());f.C("runtime","add-stylesheet",c=>this.Rf(c));f.C("runtime","alert",c=>this.Rc(c));f.C("runtime","hide-cordova-splash",()=>this.dg());f.C("runtime","set-exporting-to-video",c=>this.Sg(c));f.C("runtime","export-to-video-progress",c=>this.$f(c));f.C("runtime","exported-to-video",c=>this.ag(c));
const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||z(k)||c.preventDefault()});const n=f.D;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);n.addEventListener("selectstart",A);n.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),n.addEventListener("pointerdown",
A)):n.addEventListener("touchstart",A);this.ub=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",I,{passive:!1});window.addEventListener("wheel",I,{passive:!1});window.addEventListener("resize",()=>this.Eg());window.addEventListener("fullscreenchange",()=>this.ab());window.addEventListener("webkitfullscreenchange",()=>this.ab());window.addEventListener("mozfullscreenchange",()=>this.ab());window.addEventListener("fullscreenerror",c=>
this.Uc(c));window.addEventListener("webkitfullscreenerror",c=>this.Uc(c));window.addEventListener("mozfullscreenerror",c=>this.Uc(c));if(f.Dc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):z(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Fg(c);this.Pa=new Set;this.dc=new WeakSet;this.ua=!1}Sf(){self.setTimeout(()=>{this.je=!0},1E3);"cordova"===this.h.u?(document.addEventListener("pause",()=>this.Yc(!0)),document.addEventListener("resume",()=>this.Yc(!1))):document.addEventListener("visibilitychange",()=>this.Yc(document.hidden));return{isSuspended:!(!document.hidden&&!J)}}zd(){window.addEventListener("focus",
()=>this.cb("window-focus"));window.addEventListener("blur",()=>{this.cb("window-blur",{parentHasFocus:O()});this.ub=0});window.addEventListener("focusin",h=>{h=h.target;(D.has(h.tagName.toLowerCase())||z(h))&&this.cb("keyboard-blur")});window.addEventListener("keydown",h=>this.Wd("keydown",h));window.addEventListener("keyup",h=>this.Wd("keyup",h));window.addEventListener("dblclick",h=>this.Vc("dblclick",h,e));window.addEventListener("wheel",h=>this.jg(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Oc(h);this.bb("pointerdown",h)}),this.h.ga&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.xb=new self.lf(()=>this.Hf(),5),this.xb.he=!0,window.addEventListener("pointerrawupdate",h=>this.pg(h))):window.addEventListener("pointermove",h=>this.bb("pointermove",h)),window.addEventListener("pointerup",h=>this.bb("pointerup",h)),window.addEventListener("pointercancel",h=>this.bb("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Oc(h);this.Wc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Wc("pointermove",h)),window.addEventListener("mouseup",h=>this.Wc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Oc(h);this.Pb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Pb("pointermove",h)),window.addEventListener("touchend",h=>this.Pb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Pb("pointercancel",h)));const f=()=>this.Zc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",
f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0);this.h.df()&&!this.h.Cc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Sc(this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}Sc(f,h){document.body.style.transform="";if(0<h){var n=document.activeElement;n&&(n=n.getBoundingClientRect(),f=(n.top+n.bottom)/2-(f-h)/
2,f>h&&(f=h),0>f&&(f=0),0<f&&(document.body.style.transform=`translateY(${-f}px)`))}}cb(f,h){w(this,f,h||null,m)}sa(){return this.h.sa()}ja(){return this.h.ja()}Eg(){if(!this.X){var f=this.sa(),h=this.ja();if(this.h.Cc()){if(this.je){if(this.ue===f&&h<this.$b){this.Ab=this.$b-h;this.Sc(this.$b,this.Ab);return}0<this.Ab&&(this.Ab=0,this.Sc(h,this.Ab))}this.ue=f;this.$b=h}this.cb("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.Za()});this.h.Dc()&&
(-1!==this.Ua&&clearTimeout(this.Ua),this.Zd(f,h,0))}}Ng(f,h,n){-1!==this.Ua&&clearTimeout(this.Ua);this.Ua=setTimeout(()=>this.Zd(f,h,n),48)}Zd(f,h,n){const c=this.sa(),k=this.ja();this.Ua=-1;c!=f||k!=h?this.cb("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.Za()}):10>n&&this.Ng(c,k,n+1)}Ag(f){this.ud=f.targetOrientation}hh(){const f=this.ud;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",
h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(f):screen.webkitLockOrientation?h=screen.webkitLockOrientation(f):screen.mozLockOrientation?h=screen.mozLockOrientation(f):screen.msLockOrientation&&(h=screen.msLockOrientation(f));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}ab(){if(!this.X){var f=d.Za();f&&"any"!==this.ud&&this.hh();w(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.sa(),
innerHeight:this.ja()})}}Uc(f){console.warn("[Construct 3] Fullscreen request failed: ",f);w(this,"fullscreenerror",{isFullscreen:d.Za(),innerWidth:this.sa(),innerHeight:this.ja()})}Yc(f){f?this.h.Jc():this.h.$c();w(this,"visibilitychange",{hidden:f})}Wd(f,h){"Backspace"===h.key&&A(h);if(!this.X){var n=b.get(h.code)||h.code;C(this,f,{code:n,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},e)}}jg(f){this.X||w(this,
"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,timeStamp:f.timeStamp},e)}Vc(f,h,n){this.X||a(h)||C(this,f,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},n)}Wc(f,h){if(!this.X&&!a(h)){var n=this.ub;"pointerdown"===f&&0!==n?f="pointermove":"pointerup"===f&&0!==h.buttons&&(f="pointermove");
C(this,f,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:n,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},e);this.ub=h.buttons;this.Vc(h.type,h,g)}}bb(f,h){if(!this.X){if(this.xb&&"pointermove"!==f){var n=this.xb;n.mb||(N(n),n.Zb=Date.now())}n=0;"mouse"===h.pointerType&&(n=this.ub);C(this,f,{pointerId:h.pointerId,
pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:n,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||0)+this.kc,movementY:(h.movementY||0)+this.lc,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},e);this.lc=this.kc=0;"mouse"===h.pointerType&&(n="mousemove","pointerdown"===f?n="mousedown":"pointerup"===f&&(n="mouseup"),
this.Vc(n,h,g),this.ub=h.buttons)}}pg(f){this.Na&&(this.kc+=this.Na.movementX||0,this.lc+=this.Na.movementY||0);this.Na=f;f=this.xb;if(-1===f.Va){var h=Date.now(),n=h-f.Zb,c=f.nh;n>=c&&f.he?(f.Zb=h,f.mb=!0,f.dd(),f.mb=!1):f.Va=self.setTimeout(f.Ee,Math.max(c-n,4))}}Hf(){this.bb("pointermove",this.Na);this.Na=null}Pb(f,h){if(!this.X)for(let n=0,c=h.changedTouches.length;n<c;++n){const k=h.changedTouches[n];C(this,f,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,
clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},e)}}Oc(f){window!==window.top&&window.focus();this.Ud(f.target)&&document.activeElement&&!this.Ud(document.activeElement)&&document.activeElement.blur()}Ud(f){return!f||f===document||f===window||f===document.body||
"canvas"===f.tagName.toLowerCase()}yf(){this.ee||(this.ee=!0,window.addEventListener("deviceorientation",f=>this.Xf(f)),window.addEventListener("deviceorientationabsolute",f=>this.Yf(f)))}xf(){this.de||(this.de=!0,window.addEventListener("devicemotion",f=>this.Wf(f)))}Xf(f){this.X||w(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},e)}Yf(f){this.X||
w(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},e)}Wf(f){if(!this.X){var h=null,n=f.acceleration;n&&(h={x:n.x||0,y:n.y||0,z:n.z||0});n=null;var c=f.accelerationIncludingGravity;c&&(n={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=f.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});w(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:n,rotationRate:c,interval:f.interval,timeStamp:f.timeStamp},
e)}}Dg(f){var h=this.h;h.nd||(h=h.D,h.style.width=f.styleWidth+"px",h.style.height=f.styleHeight+"px",h.style.marginLeft=f.marginLeft+"px",h.style.marginTop=f.marginTop+"px",this.qe&&(h.style.display="",this.qe=!1))}fg(f){const h=f.url;f=f.filename;const n=document.createElement("a"),c=document.body;n.textContent=f;n.href=h;n.download=f;c.appendChild(n);n.click();c.removeChild(n)}async rg(f){var h=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,
f.surfaceHeight);h=h?await createImageBitmap(f,h):await createImageBitmap(f);return{imageBitmap:h,transferables:[h]}}async cg(f){return await self.C3_GetSvgImageSize(f.blob)}async Rf(f){await q(f.url)}Zc(){var f=[...this.Pa];this.Pa.clear();if(!this.ua)for(const h of f)(f=h.play())&&f.catch(()=>{this.dc.has(h)||this.Pa.add(h)})}Z(f){if("function"!==typeof f.play)throw Error("missing play function");this.dc.delete(f);let h;try{h=f.play()}catch(n){this.Pa.add(f);return}h&&h.catch(()=>{this.dc.has(f)||
this.Pa.add(f)})}ba(f){this.Pa.delete(f);this.dc.add(f)}Kb(f){this.ua=!!f}dg(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Vf(f){if(f.show){this.Da||(this.Da=document.createElement("div"),this.Da.id="inspectOutline",document.body.appendChild(this.Da));var h=this.Da;h.style.display="";h.style.left=f.left-1+"px";h.style.top=f.top-1+"px";h.style.width=f.width+2+"px";h.style.height=f.height+2+"px";h.textContent=f.name}else this.Da&&(this.Da.style.display="none")}sg(){window.C3_RegisterSW&&
window.C3_RegisterSW()}Yd(f){window.c3_postToMessagePort&&(f.from="runtime",window.c3_postToMessagePort(f))}Pf(f,h){return this.h.Jd(this.hb,"js-invoke-function",{name:f,params:h},void 0,void 0)}Rc(f){alert(f.message)}Fg(f){"entered-fullscreen"===f?(d.Sb(!0),this.ab()):"exited-fullscreen"===f?(d.Sb(!1),this.ab()):console.warn("Unknown wrapper message: ",f)}Sg(f){this.X=!0;const h=document.createElement("h1");h.id="exportToVideoMessage";h.textContent=f.message;document.body.prepend(h);document.body.classList.add("exportingToVideo");
this.h.D.style.display="";this.h.pf(f.duration)}$f(f){this.le=f.message;-1===this.hd&&(this.hd=setTimeout(()=>this.If(),250))}If(){this.hd=-1;const f=document.getElementById("exportToVideoMessage");f&&(f.textContent=this.le)}ag(f){window.Lh({type:"exported-video",blob:f.blob,time:f.time})}})}"use strict";
async function T(d){if(d.mh)throw Error("already initialised");d.mh=!0;var a=d.oc.Nc("dispatchworker.js");d.gd=await d.oc.wc(a,d.gb,{name:"DispatchWorker"});a=new MessageChannel;d.md=a.port1;d.gd.postMessage({type:"_init","in-port":a.port2},[a.port2]);d.td=await U(d)}function ba(d){return[d.md,d.td]}
async function U(d){const a=d.re.length;var b=d.oc.Nc("jobworker.js");b=await d.oc.wc(b,d.gb,{name:"JobWorker"+a});const e=new MessageChannel,g=new MessageChannel;d.gd.postMessage({type:"_addJobWorker",port:e.port1},[e.port1]);b.postMessage({type:"init",number:a,"dispatch-port":e.port2,"output-port":g.port2},[e.port2,g.port2]);d.re.push(b);return g.port1}
self.gf=class{constructor(d){this.oc=d;this.gb=d.$;this.gb="preview"===d.u?this.gb+"workers/":this.gb+d.pc;this.ph=Math.min(navigator.hardwareConcurrency||2,16);this.gd=null;this.re=[];this.td=this.md=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ca({Fh:!0,Gh:"workermain.js",Wa:["scripts/c3runtime.js"],tc:[],wd:"",Ch:"scripts/",yd:[],Fe:"html5"}));"use strict";
{function d(a){a.stopPropagation()}self.ca.ya(class extends self.Dd{constructor(a){super(a,"button")}vc(a,b){const e=document.createElement("input");var g=e;b.isCheckbox?(e.type="checkbox",g=document.createElement("label"),g.appendChild(e),g.appendChild(document.createTextNode("")),g.style.fontFamily="sans-serif",g.style.userSelect="none",g.style.webkitUserSelect="none",g.style.display="inline-block",g.style.color="black"):e.type="button";g.style.position="absolute";g.addEventListener("pointerdown",
d);g.addEventListener("pointermove",d);g.addEventListener("pointerrawupdate",d);g.addEventListener("pointerup",d);g.addEventListener("mousedown",d);g.addEventListener("mouseup",d);g.addEventListener("keydown",d);g.addEventListener("keyup",d);e.addEventListener("click",()=>{var m={isChecked:e.checked};m.elementId=a;C(this,"click",m)});b.id&&(e.id=b.id);b.className&&(e.className=b.className);this.Mb(g,b);return g}Sd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}Mc(a){return this.Sd(a)}Mb(a,
b){const e=this.Sd(a);e.checked=b.isChecked;e.disabled=!b.isEnabled;a.title=b.title;a===e?e.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
self.ca.ya(class extends self.Dd{constructor(d){super(d,"video");this.yb=this.qc=this.pd=this.fb=!1;this.ec=this.th=0;this.fd=new WeakSet;F(this,"init",a=>this.eg(a));S(this,"play",a=>this.og(a));S(this,"pause",a=>this.ng(a));S(this,"set-source",(a,b)=>this.zg(a,b));S(this,"set-playback-time",(a,b)=>this.yg(a,b));S(this,"set-playback-rate",(a,b)=>this.xg(a,b));S(this,"set-looping",(a,b)=>this.vg(a,b));S(this,"set-muted",(a,b)=>this.wg(a,b));S(this,"set-volume",(a,b)=>this.Bg(a,b));self.C3Video_GetElement=
a=>this.U.get(a)}async eg(d){this.pd=d.isInWorker;d=document.createElement("video");this.qc=!!d.requestVideoFrameCallback&&!this.h.Cc();const a=!!self.createImageBitmap;this.yb=this.pd||a;return{postImageBitmaps:this.yb,supportedFormats:{"video/webm":!!d.canPlayType("video/webm"),"video/ogg":!!d.canPlayType("video/ogg"),"video/mp4":!!d.canPlayType("video/mp4")}}}Z(d){this.h.Z(d);this.yb&&this.qc&&-1===d.c3_rvfcId&&(d.c3_rvfcId=d.requestVideoFrameCallback(()=>this.$d(d)))}ba(d){this.h.ba(d);this.yb&&
this.qc&&-1!==d.c3_rvfcId&&(d.cancelVideoFrameCallback(d.c3_rvfcId),d.c3_rvfcId=-1)}async $d(d){if(!this.fd.has(d)){d.c3_rvfcId=d.requestVideoFrameCallback(()=>this.$d(d));try{const a=d.c3_sequenceNumber++,b=await createImageBitmap(d);a>d.c3_lastFrameSequence&&(d.c3_imageBitmap=b,d.c3_lastFrameSequence=a)}catch(a){}}}vc(d,a){const b=document.createElement("video");b.crossOrigin="anonymous";b.playsInline=!0;b.c3_imageBitmap=null;b.c3_rvfcId=-1;b.c3_sequenceNumber=0;b.c3_lastFrameSequence=-1;b.addEventListener("canplay",
()=>this.ta(b,d,0));b.addEventListener("canplaythrough",()=>this.ta(b,d,1));b.addEventListener("ended",()=>this.ta(b,d,2));b.addEventListener("error",()=>this.ta(b,d,3));b.addEventListener("loadstart",()=>this.ta(b,d,4));b.addEventListener("playing",()=>this.ta(b,d,5));b.addEventListener("pause",()=>this.ta(b,d,6));b.addEventListener("stalled",()=>this.ta(b,d,7));const e=a.autoplay;0===e?(b.autoplay=!1,b.preload="none"):1===e?(b.autoplay=!1,b.preload="auto"):b.autoplay=!0;a.src&&(b.src=a.src);2===
e&&this.Z(b);this.ec++;L(this);return b}ta(d,a,b){this.fd.has(d)||R(this,"playback-event",a,{type:b})}Mb(){}Fd(d){this.ba(d);d&&!d.paused&&!d.ended&&0<d.currentTime&&d.pause();d.src="";this.ec=Math.max(this.ec-1,0);0===this.ec&&M(this);this.fd.add(d)}og(d){this.Z(d)}ng(d){this.ba(d);d.pause()}zg(d,a){d.src=a.src;d.load()}yg(d,a){try{d.currentTime=a.time}catch(b){console.error("[Video] Exception setting playback time: ",b)}}xg(d,a){try{d.playbackRate=a.rate}catch(b){console.error("[Video] Exception setting playback rate: ",
b)}}vg(d,a){d.loop=a.isLooping}wg(d,a){d.muted=a.isMuted}Bg(d,a){d.volume=a.volume}Ba(){const d={},a={sequenceNumber:this.th++,videoData:d},b=[],e=[];for(const [g,m]of this.U.entries()){const q={currentTime:m.currentTime,playbackRate:m.playbackRate,duration:m.duration,videoWidth:m.videoWidth,videoHeight:m.videoHeight};if(this.yb)if(this.qc){const u=m.c3_imageBitmap;m.c3_imageBitmap=null;(q.imageBitmap=u)&&b.push(u)}else e.push(createImageBitmap(m).then(u=>{q.imageBitmap=u;b.push(u)}).catch(()=>{q.imageBitmap=
null}));d[g.toString()]=q}Promise.all(e).then(()=>{this.pd?w(this,"state",a,!1,b):C(this,"state",a)})}});"use strict";
self.ca.ya(class extends self.Ga{constructor(d){super(d,"mouse");K(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.h.D.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{w(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{w(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function da(d,a){a=a.type;let b=!0;0===a?b=await ea():1===a&&(b=await fa());w(d,"permission-result",{type:a,result:b})}async function ea(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}
async function fa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}self.ca.ya(class extends self.Ga{constructor(d){super(d,"touch");F(this,"request-permission",a=>da(this,a))}});"use strict";
function ia(d){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>w(d,"sw-message",a.data))}
function ja(d){d=d.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(d):screen.webkitLockOrientation?a=screen.webkitLockOrientation(d):screen.mozLockOrientation?a=screen.mozLockOrientation(d):screen.msLockOrientation&&(a=screen.msLockOrientation(d));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ca.ya(class extends self.Ga{constructor(d){super(d,"browser");this.u="";K(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
ia(this)],["alert",a=>this.Rc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Xc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ja(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const e=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,
"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Kh||(2===e?window.top.location=b:1===e?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.ca.Sb(!0),this.h.ad({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===
a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.u||"macos-wkwebview"===this.u?(self.ca.Sb(!1),this.h.ad({type:"set-fullscreen",
fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{w(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{w(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{w(this,"hashchange",
{location:location.toString()})});document.addEventListener("backbutton",()=>{w(this,"backbutton")})}Rc(d){alert(d.message)}Xc(d){d=d.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;d?a.focus():a.blur()}else d?window.focus():window.blur()}});"use strict";
{const d=180/Math.PI;self.ha=class extends self.Ga{constructor(a){super(a,"audio");this.La=this.a=null;this.Xb=this.ld=!1;this.xa=()=>this.ih();this.ea=[];this.J=[];this.la=null;this.se="";this.te=-1;this.wb=new Map;this.cc=1;this.ua=!1;this.vd=0;this.rc=1;this.jd=0;this.we="HRTF";this.ie="inverse";this.xe=600;this.ve=1E4;this.ze=1;this.ne=this.ic=!1;this.Ce=this.h.ef();this.fa=new Map;this.Ka=new Set;this.oe=this.od=!1;this.rd="";this.Ea=null;self.C3Audio_OnMicrophoneStream=(b,e)=>this.ig(b,e);this.Vb=
null;self.C3Audio_GetOutputStream=()=>this.bg();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.Df(b)],["play",b=>this.Hg(b)],["stop",b=>this.fh(b)],["stop-all",()=>this.gh()],["set-paused",b=>this.Yg(b)],["set-volume",b=>this.dh(b)],["fade-volume",b=>this.Jf(b)],["set-master-volume",b=>this.Wg(b)],["set-muted",b=>this.Xg(b)],["set-silent",b=>this.$g(b)],["set-looping",b=>this.Vg(b)],["set-playback-rate",b=>this.Zg(b)],["seek",b=>this.Og(b)],["preload",b=>this.Ig(b)],["unload",
b=>this.jh(b)],["unload-all",()=>this.kh()],["set-suspended",b=>this.ah(b)],["add-effect",b=>this.Od(b)],["set-effect-param",b=>this.Rg(b)],["remove-effects",b=>this.Kg(b)],["tick",b=>this.Cg(b)],["load-state",b=>this.gg(b)],["offline-render-audio",b=>this.kg(b)],["offline-render-finish",()=>this.mg()]])}async Df(a){a.isiOSCordova&&(this.ic=!0);this.vd=a.timeScaleMode;this.we=["equalpower","HRTF","soundfield"][a.panningModel];this.ie=["linear","inverse","exponential"][a.distanceModel];this.xe=a.refDistance;
this.ve=a.maxDistance;this.ze=a.rolloffFactor;if(this.h.nd)this.ic=!0,this.a=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*this.h.ke)});else{var b={latencyHint:a.latencyHint};this.Ce||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.a=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.a=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Pd();this.a.onstatechange=()=>{"running"!==this.a.state&&this.Pd();
w(this,"audiocontext-state",{audioContextState:this.a.state})}}this.La=this.a.createGain();this.La.connect(this.a.destination);b=a.listenerPos;this.a.listener.setPosition(b[0],b[1],b[2]);this.a.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.xc();try{await Promise.all(a.preloadList.map(e=>this.Nb(e.originalUrl,e.url,e.type,!1)))}catch(e){console.error("[Construct 3] Preloading sounds failed: ",e)}return{sampleRate:this.a.sampleRate,audioContextState:this.a.state}}Pd(){this.Xb||
(this.ld=!1,window.addEventListener("pointerup",this.xa,!0),window.addEventListener("touchend",this.xa,!0),window.addEventListener("click",this.xa,!0),window.addEventListener("keydown",this.xa,!0),this.Xb=!0)}Ff(){this.Xb&&(this.ld=!0,window.removeEventListener("pointerup",this.xa,!0),window.removeEventListener("touchend",this.xa,!0),window.removeEventListener("click",this.xa,!0),window.removeEventListener("keydown",this.xa,!0),this.Xb=!1)}ih(){if(!this.ld){var a=this.a;"suspended"===a.state&&a.resume&&
a.resume();var b=a.createBuffer(1,220,22050),e=a.createBufferSource();e.buffer=b;e.connect(a.destination);e.start(0);"running"===a.state&&this.Ff()}}W(){return this.a}xc(){return this.a.currentTime}za(){return this.La}Gd(a){return(a=this.fa.get(a.toLowerCase()))?a[0].O():this.za()}Ge(a,b){a=a.toLowerCase();let e=this.fa.get(a);e||(e=[],this.fa.set(a,e));b.Ug(e.length);b.bh(a);e.push(b);this.be(a)}be(a){let b=this.za();const e=this.fa.get(a);if(e&&e.length){b=e[0].O();for(let g=0,m=e.length;g<m;++g){const q=
e[g];g+1===m?q.R(this.za()):q.R(e[g+1].O())}}for(const g of this.qa(a))g.mf(b);this.Ea&&this.rd===a&&(this.Ea.disconnect(),this.Ea.connect(b))}Gb(){return this.ua}Tg(){this.ne=!0}Ye(a,b){return b?this.h.lh(a).then(e=>{const g=this.a.createBuffer(1,e.length,48E3);g.getChannelData(0).set(e);return g}):new Promise((e,g)=>{this.a.decodeAudioData(a,e,g)})}Z(a){this.h.Z(a)}ba(a){this.h.ba(a)}Kd(a){let b=0;for(let e=0,g=this.J.length;e<g;++e){const m=this.J[e];this.J[b]=m;m.K===a?m.f():++b}this.J.length=
b}nf(){let a=0;for(let b=0,e=this.ea.length;b<e;++b){const g=this.ea[b];this.ea[a]=g;g.Aa()?g.f():++a}this.ea.length=a}*qa(a){if(a)for(const b of this.J)self.ha.Ze(b.aa,a)&&(yield b);else this.la&&!this.la.S()&&(yield this.la)}async Nb(a,b,e,g,m){for(const q of this.ea)if(q.Ya()===b)return await V(q),q;if(m)return null;g&&(this.ic||this.ne)&&this.nf();m="audio/webm; codecs=opus"===e&&!this.Ce;g&&m&&this.Tg();a=!g||this.ic||m?new self.Ue(this,a,b,e,g,m):new self.Se(this,a,b,e,g);this.ea.push(a);await V(a);
return a}async Lc(a,b,e,g,m){for(const q of this.J)if(q.Ya()===b&&(q.uc()||m))return q.rf(g),q;a=await this.Nb(a,b,e,m);g="html5"===a.cd?new self.Te(a.l,a,g):new self.Ve(a.l,a,g);this.J.push(g);return g}vf(a){let b=this.wb.get(a);if(!b){let e=null;b={xd:0,Ah:new Promise(g=>e=g),resolve:e};this.wb.set(a,b)}b.xd++}Lg(a){const b=this.wb.get(a);if(!b)throw Error("expected pending tag");b.xd--;0===b.xd&&(b.resolve(),this.wb.delete(a))}Ic(a){a||(a=this.se);return(a=this.wb.get(a))?a.Ah:Promise.resolve()}Ob(){if(0<
this.Ka.size)L(this);else for(const a of this.J)if(a.Hd()){L(this);break}}Ba(){for(var a of this.Ka)a.Ba();a=this.xc();for(var b of this.J)b.Ba(a);b=this.J.filter(e=>e.Hd()).map(e=>e.Xa());w(this,"state",{tickCount:this.te,audioInstances:b,analysers:[...this.Ka].map(e=>e.af())});0===b.length&&0===this.Ka.size&&M(this)}Ec(a,b,e){w(this,"trigger",{type:a,tag:b,aiid:e})}async Hg(a){const b=a.originalUrl,e=a.url,g=a.type,m=a.isMusic,q=a.tag,u=a.isLooping,B=a.vol,G=a.pos,y=a.panning;let z=a.off;0<z&&!a.trueClock&&
(this.a.getOutputTimestamp?(a=this.a.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+this.a.currentTime);this.se=q;this.vf(q);try{this.la=await this.Lc(b,e,g,q,m),y?(this.la.Jb(!0),this.la.qf(y.x,y.y,y.angle,y.innerAngle,y.outerAngle,y.outerGain),y.hasOwnProperty("uid")&&this.la.sf(y.uid)):this.la.Jb(!1),this.la.Play(u,B,G,z)}catch(D){console.error("[Construct 3] Audio: error starting playback: ",D);return}finally{this.Lg(q)}L(this)}fh(a){a=a.tag;for(const b of this.qa(a))b.ra()}gh(){for(const a of this.J)a.ra()}Yg(a){const b=
a.tag;a=a.paused;for(const e of this.qa(b))a?e.$a():e.Ib();this.Ob()}dh(a){const b=a.tag;a=a.vol;for(const e of this.qa(b))e.Lb(a)}async Jf(a){const b=a.tag,e=a.vol,g=a.duration;a=a.stopOnEnd;await this.Ic(b);for(const m of this.qa(b))m.$e(e,g,a);this.Ob()}Wg(a){this.cc=a.vol;this.La.gain.value=this.cc}Xg(a){const b=a.tag;a=a.isMuted;for(const e of this.qa(b))e.Ld(a)}$g(a){this.ua=a.isSilent;this.h.Kb(this.ua);for(const b of this.J)b.Tb()}Vg(a){const b=a.tag;a=a.isLooping;for(const e of this.qa(b))e.Gc(a)}async Zg(a){const b=
a.tag;a=a.rate;await this.Ic(b);for(const e of this.qa(b))e.Nd(a)}async Og(a){const b=a.tag;a=a.pos;await this.Ic(b);for(const e of this.qa(b))e.Fc(a)}async Ig(a){const b=a.originalUrl,e=a.url,g=a.type;a=a.isMusic;try{await this.Lc(b,e,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async jh(a){if(a=await this.Nb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.ea.indexOf(a),-1!==a&&this.ea.splice(a,1)}kh(){for(const a of this.ea)a.f();this.ea.length=0}ah(a){a=a.isSuspended;
!a&&this.a.resume&&this.a.resume();for(const b of this.J)b.Hc(a);a&&this.a.suspend&&this.a.suspend()}Cg(a){this.rc=a.timeScale;this.jd=a.gameTime;this.te=a.tickCount;if(0!==this.vd)for(var b of this.J)b.Ja();(b=a.listenerPos)&&this.a.listener.setPosition(b[0],b[1],b[2]);for(const e of a.instPans){a=e.uid;for(const g of this.J)g.ka===a&&g.Md(e.x,e.y,e.angle)}}async Od(a){var b=a.type;const e=a.tag;var g=a.params;if("filter"===b)g=new self.Me(this,...g);else if("delay"===b)g=new self.Ke(this,...g);
else if("convolution"===b){b=null;try{b=await this.Nb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}g=new self.Je(this,b.da,...g);g.Pg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.Ne(this,...g);else if("phaser"===b)g=new self.Pe(this,...g);else if("gain"===b)g=new self.Oe(this,...g);else if("tremolo"===b)g=new self.Re(this,...g);else if("ringmod"===b)g=new self.Qe(this,...g);else if("distortion"===
b)g=new self.Le(this,...g);else if("compressor"===b)g=new self.Ie(this,...g);else if("analyser"===b)g=new self.He(this,...g);else throw Error("invalid effect type");this.Ge(e,g);this.ae()}Rg(a){const b=a.index,e=a.param,g=a.value,m=a.ramp,q=a.time;a=this.fa.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(e,g,m,q),this.ae())}Kg(a){a=a.tag.toLowerCase();const b=this.fa.get(a);if(b&&b.length){for(const e of b)e.f();this.fa.delete(a);this.be(a)}}uf(a){this.Ka.add(a);this.Ob()}Jg(a){this.Ka.delete(a)}ae(){this.od||
(this.od=!0,Promise.resolve().then(()=>this.Gf()))}Gf(){const a={};for(const [b,e]of this.fa)a[b]=e.map(g=>g.Xa());w(this,"fxstate",{fxstate:a});this.od=!1}async gg(a){const b=a.saveLoadMode;if(3!==b)for(var e of this.J)e.Aa()&&1===b||(e.Aa()||2!==b)&&e.ra();for(const g of this.fa.values())for(const m of g)m.f();this.fa.clear();this.rc=a.timeScale;this.jd=a.gameTime;e=a.listenerPos;this.a.listener.setPosition(e[0],e[1],e[2]);this.ua=a.isSilent;this.h.Kb(this.ua);this.cc=a.masterVolume;this.La.gain.value=
this.cc;e=[];for(const g of Object.values(a.effects))e.push(Promise.all(g.map(m=>this.Od(m))));await Promise.all(e);await Promise.all(a.playing.map(g=>this.Qf(g,b)));this.Ob()}async Qf(a,b){if(3!==b){var e=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,q=a.isMusic,u=a.tag,B=a.isLooping,G=a.volume,y=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Lc(e,g,m,u,q)}catch(z){console.error("[Construct 3] Audio: error loading audio state: ",z);return}b.kf(a.pan);b.Play(B,G,y,0);a.isPlaying||
b.$a();b.Qc(a)}}}ig(a,b){this.Ea&&this.Ea.disconnect();this.rd=b.toLowerCase();this.Ea=this.a.createMediaStreamSource(a);this.Ea.connect(this.Gd(this.rd))}bg(){this.Vb||(this.Vb=this.a.createMediaStreamDestination(),this.La.connect(this.Vb));return this.Vb.stream}async kg(a){try{const b=this.a.suspend(a.time);this.oe?this.a.resume():(this.a.startRendering().then(e=>this.lg(e)).catch(e=>this.Xd(e)),this.oe=!0);await b}catch(b){this.Xd(b)}}mg(){this.a.resume()}lg(a){const b=[];for(let e=0,g=a.numberOfChannels;e<
g;++e){const m=a.getChannelData(e);b.push(m.buffer)}this.h.Hb("runtime","offline-audio-render-completed",{duration:a.duration,length:a.length,numberOfChannels:a.numberOfChannels,sampleRate:a.sampleRate,channelData:b},null,b)}Xd(a){console.error("[Audio] Offline rendering error: ",a)}static Ze(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static tf(a){return a*d}static Xe(a){return Math.pow(10,a/20)}static Ed(a){return Math.max(Math.min(self.ha.Xe(a),1),0)}static jf(a){return Math.log(a)/
Math.log(10)*20}static hf(a){return self.ha.jf(Math.max(Math.min(a,1),0))}static vh(a,b){return 1-Math.exp(-b*a)}};self.ca.ya(self.ha)}"use strict";function V(d){d.ac||(d.ac=d.Pc());return d.ac}self.Ad=class{constructor(d,a,b,e,g){this.l=d;this.rh=a;this.Fa=b;this.P=e;this.oh=g;this.cd="";this.ac=null}f(){this.ac=this.l=null}Pc(){}W(){return this.l.W()}zc(){return this.rh}Ya(){return this.Fa}yc(){return this.P}Aa(){return this.oh}ia(){}};"use strict";
self.Se=class extends self.Ad{constructor(d,a,b,e,g){super(d,a,b,e,g);this.cd="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.qb=this.rb=null;this.I.addEventListener("canplaythrough",()=>!0);this.vb=this.W().createGain();this.tb=null;this.I.addEventListener("canplay",()=>{this.rb&&(this.rb(),this.qb=this.rb=null);!this.tb&&this.I&&(this.tb=this.W().createMediaElementSource(this.I),this.tb.connect(this.vb))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Fa}' error: `,m);this.qb&&(this.qb(m),this.qb=this.rb=null)})}f(){this.l.Kd(this);this.vb.disconnect();this.vb=null;this.tb.disconnect();this.tb=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.f()}Pc(){return new Promise((d,a)=>{this.rb=d;this.qb=a;this.I.src=this.Fa})}N(){return this.I}ia(){return this.I.duration}};"use strict";
async function ka(d){if(d.Ca)return d.Ca;var a=d.l.h;if("cordova"===a.u&&a.Id(d.Fa)&&a.nb)d.Ca=await a.Eb(d.Fa);else{a=await fetch(d.Fa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);d.Ca=await a.arrayBuffer()}}async function la(d){if(d.da)return d.da;d.da=await d.l.Ye(d.Ca,d.qh);d.Ca=null}
self.Ue=class extends self.Ad{constructor(d,a,b,e,g,m){super(d,a,b,e,g);this.cd="webaudio";this.da=this.Ca=null;this.qh=!!m}f(){this.l.Kd(this);this.da=this.Ca=null;super.f()}async Pc(){try{await ka(this),await la(this)}catch(d){console.error(`[Construct 3] Failed to load audio '${this.Fa}': `,d)}}ia(){return this.da?this.da.duration:0}};"use strict";
{let d=0;self.Bd=class{constructor(a,b,e){this.l=a;this.K=b;this.aa=e;this.Ub=d++;this.L=this.W().createGain();this.L.connect(this.za());this.B=null;this.ob=!1;this.oa=[0,0,0];this.na=[0,0,0];this.G=!0;this.V=this.pa=this.F=!1;this.Bb=1;this.Ma=!1;this.wa=1;a=this.l.vd;this.qd=1===a&&!this.Aa()||2===a;this.kb=this.ka=-1;this.Be=!1}f(){this.K=this.l=null;this.B&&(this.B.disconnect(),this.B=null);this.L.disconnect();this.L=null}W(){return this.l.W()}za(){return this.l.Gd(this.aa)}Fb(){return this.qd?
this.l.jd:performance.now()/1E3}zc(){return this.K.zc()}Ya(){return this.K.Ya()}yc(){return this.K.yc()}Aa(){return this.K.Aa()}rf(a){this.aa=a}S(){}uc(){}IsPlaying(){return!this.G&&!this.F&&!this.S()}Hd(){return!this.G&&!this.S()}Ha(){}ia(){return this.K.ia()}Play(){}ra(){}$a(){}Ib(){}Lb(a){this.Bb=a;this.L.gain.cancelScheduledValues(0);this.kb=-1;this.L.gain.value=this.Ac()}$e(a,b,e){if(!this.Ma){var g=this.L.gain;g.cancelScheduledValues(0);var m=this.l.xc();b=m+b;g.setValueAtTime(g.value,m);g.linearRampToValueAtTime(a,
b);this.Bb=a;this.kb=b;this.Be=e}}bd(){this.Lb(this.Bb)}Ba(a){-1!==this.kb&&a>=this.kb&&(this.kb=-1,this.Be&&this.ra(),this.l.Ec("fade-ended",this.aa,this.Ub))}Ac(){const a=this.Bb;return isFinite(a)?a:0}Ld(a){a=!!a;this.Ma!==a&&(this.Ma=a,this.Tb())}Gb(){return this.l.Gb()}Tb(){}Gc(){}Nd(a){this.wa!==a&&(this.wa=a,this.Ja())}Ja(){}Fc(){}Hc(){}Jb(a){a=!!a;this.ob!==a&&((this.ob=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.l.we,this.B.distanceModel=this.l.ie,this.B.refDistance=
this.l.xe,this.B.maxDistance=this.l.ve,this.B.rolloffFactor=this.l.ze),this.L.disconnect(),this.L.connect(this.B),this.B.connect(this.za())):(this.B.disconnect(),this.L.disconnect(),this.L.connect(this.za())))}qf(a,b,e,g,m,q){this.ob&&(this.Md(a,b,e),a=self.ha.tf,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=q)}Md(a,b,e){this.ob&&(this.oa[0]=a,this.oa[1]=b,this.oa[2]=0,this.na[0]=Math.cos(e),this.na[1]=Math.sin(e),this.na[2]=0,this.B.setPosition(...this.oa),this.B.setOrientation(...this.na))}sf(a){this.ka=
a}Bc(){}mf(a){const b=this.B||this.L;b.disconnect();b.connect(a)}Xa(){return{aiid:this.Ub,tag:this.aa,duration:this.ia(),volume:this.Bb,isPlaying:this.IsPlaying(),playbackTime:this.Ha(),playbackRate:this.wa,uid:this.ka,bufferOriginalUrl:this.zc(),bufferUrl:"",bufferType:this.yc(),isMusic:this.Aa(),isLooping:this.V,isMuted:this.Ma,resumePosition:this.Bc(),pan:this.bf()}}Qc(a){this.Nd(a.playbackRate);this.Ld(a.isMuted)}bf(){if(!this.B)return null;const a=this.B;return{pos:this.oa,orient:this.na,cia:a.coneInnerAngle,
coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ka}}kf(a){if(a){this.Jb(!0);a=this.B;var b=a.pos;this.oa[0]=b[0];this.oa[1]=b[1];this.oa[2]=b[2];b=a.orient;this.na[0]=b[0];this.na[1]=b[1];this.na[2]=b[2];a.setPosition(...this.oa);a.setOrientation(...this.na);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ka=a.uid}else this.Jb(!1)}}}"use strict";
self.Te=class extends self.Bd{constructor(d,a,b){super(d,a,b);this.K.vb.connect(this.L);this.K.onended=()=>this.Tc()}f(){this.ra();this.K.vb.disconnect();super.f()}N(){return this.K.N()}Tc(){this.G=!0;this.ka=-1;this.l.Ec("ended",this.aa,this.Ub)}S(){return this.N().ended}uc(){return this.G?!0:this.S()}Ha(){let d=this.N().currentTime;this.V||(d=Math.min(d,this.ia()));return d}Play(d,a,b){const e=this.N();1!==e.playbackRate&&(e.playbackRate=1);e.loop!==d&&(e.loop=d);this.Lb(a);e.muted&&(e.muted=!1);
if(e.currentTime!==b)try{e.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.K.Ya()}' to position '${b}': `,g)}this.l.Z(e);this.F=this.G=!1;this.V=d;this.wa=1}ra(){const d=this.N();d.paused||d.pause();this.l.ba(d);this.G=!0;this.F=!1;this.ka=-1}$a(){if(!(this.F||this.G||this.S())){var d=this.N();d.paused||d.pause();this.l.ba(d);this.F=!0}}Ib(){!this.F||this.G||this.S()||(this.l.Z(this.N()),this.F=!1)}Tb(){this.N().muted=this.Ma||this.Gb()}Gc(d){d=!!d;this.V!==d&&(this.V=
d,this.N().loop=d)}Ja(){let d=this.wa;this.qd&&(d*=this.l.rc);try{this.N().playbackRate=d}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${d}':`,a)}}Fc(d){if(!this.G&&!this.S())try{this.N().currentTime=d}catch(a){console.warn(`[Construct 3] Error seeking audio to '${d}': `,a)}}Bc(){return this.Ha()}Hc(d){d?this.IsPlaying()?(this.N().pause(),this.pa=!0):this.pa=!1:this.pa&&(this.l.Z(this.N()),this.pa=!1)}};"use strict";function W(d){d.j&&d.j.disconnect();d.j=null;d.eb=null}
self.Ve=class extends self.Bd{constructor(d,a,b){super(d,a,b);this.j=null;this.fc=e=>this.Tc(e);this.kd=!0;this.eb=null;this.M=this.hc=this.jc=0;this.sd=1}f(){this.ra();W(this);this.fc=null;super.f()}Tc(d){this.F||this.pa||d.target!==this.eb||(this.G=this.kd=!0,this.ka=-1,W(this),this.l.Ec("ended",this.aa,this.Ub))}S(){return!this.G&&this.j&&this.j.loop||this.F?!1:this.kd}uc(){return!this.j||this.G?!0:this.S()}Ha(){let d;d=this.F?this.M:this.hc+(this.Fb()-this.jc)*this.wa;this.V||(d=Math.min(d,this.ia()));
return d}Play(d,a,b,e){this.sd=1;this.Lb(a);W(this);this.j=this.W().createBufferSource();this.j.buffer=this.K.da;this.j.connect(this.L);this.eb=this.j;this.j.onended=this.fc;this.j.loop=d;this.j.start(e,b);this.F=this.G=this.kd=!1;this.V=d;this.wa=1;this.jc=this.Fb();this.hc=b}ra(){if(this.j)try{this.j.stop(0)}catch(d){}this.G=!0;this.F=!1;this.ka=-1}$a(){this.F||this.G||this.S()||(this.M=this.Ha(),this.V&&(this.M%=this.ia()),this.F=!0,this.j.stop(0))}Ib(){!this.F||this.G||this.S()||(W(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.K.da,this.j.connect(this.L),this.eb=this.j,this.j.onended=this.fc,this.j.loop=this.V,this.bd(),this.Ja(),this.j.start(0,this.M),this.jc=this.Fb(),this.hc=this.M,this.F=!1)}Ac(){return super.Ac()*this.sd}Tb(){this.sd=this.Ma||this.Gb()?0:1;this.bd()}Gc(d){d=!!d;this.V!==d&&(this.V=d,this.j&&(this.j.loop=d))}Ja(){let d=this.wa;this.qd&&(d*=this.l.rc);this.j&&(this.j.playbackRate.value=d)}Fc(d){this.G||this.S()||(this.F?this.M=d:(this.$a(),this.M=d,this.Ib()))}Bc(){return this.M}Hc(d){d?
this.IsPlaying()?(this.pa=!0,this.M=this.Ha(),this.V&&(this.M%=this.ia()),this.j.stop(0)):this.pa=!1:this.pa&&(W(this),this.j=this.W().createBufferSource(),this.j.buffer=this.K.da,this.j.connect(this.L),this.eb=this.j,this.j.onended=this.fc,this.j.loop=this.V,this.bd(),this.Ja(),this.j.start(0,this.M),this.jc=this.Fb(),this.hc=this.M,this.pa=!1)}Qc(d){super.Qc(d);this.M=d.resumePosition}};"use strict";
{class d{constructor(a){this.l=a;this.a=a.W();this.pe=-1;this.P=this.aa="";this.g=null}f(){this.a=null}Ug(a){this.pe=a}bh(a){this.aa=a}s(){return this.a.createGain()}O(){}R(){}o(a,b,e,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.a.currentTime;g+=m;switch(e){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Xa(){return{type:this.P,tag:this.aa,params:this.g}}}
self.Me=class extends d{constructor(a,b,e,g,m,q,u){super(a);this.P="filter";this.g=[b,e,g,m,q,u];this.m=this.s();this.c=this.s();this.c.gain.value=u;this.b=this.s();this.b.gain.value=1-u;this.A=this.a.createBiquadFilter();this.A.type=b;this.A.frequency.value=e;this.A.detune.value=g;this.A.Q.value=m;this.A.gain.vlaue=q;this.m.connect(this.A);this.m.connect(this.b);this.A.connect(this.c)}f(){this.m.disconnect();this.A.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();
this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.m}Y(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.o(this.c.gain,b,e,g);this.o(this.b.gain,1-b,e,g);break;case 1:this.g[1]=b;this.o(this.A.frequency,b,e,g);break;case 2:this.g[2]=b;this.o(this.A.detune,b,e,g);break;case 3:this.g[3]=b;this.o(this.A.Q,b,e,g);break;case 4:this.g[4]=b,this.o(this.A.gain,b,e,g)}}};self.Ke=class extends d{constructor(a,b,e,g){super(a);this.P="delay";this.g=[b,e,g];this.m=
this.s();this.c=this.s();this.c.gain.value=g;this.b=this.s();this.b.gain.value=1-g;this.sb=this.s();this.T=this.a.createDelay(b);this.T.delayTime.value=b;this.jb=this.s();this.jb.gain.value=e;this.m.connect(this.sb);this.m.connect(this.b);this.sb.connect(this.c);this.sb.connect(this.T);this.T.connect(this.jb);this.jb.connect(this.sb)}f(){this.m.disconnect();this.c.disconnect();this.b.disconnect();this.sb.disconnect();this.T.disconnect();this.jb.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);
this.b.disconnect();this.b.connect(a)}O(){return this.m}Y(a,b,e,g){const m=self.ha.Ed;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.o(this.c.gain,b,e,g);this.o(this.b.gain,1-b,e,g);break;case 4:this.g[1]=m(b);this.o(this.jb.gain,m(b),e,g);break;case 5:this.g[0]=b,this.o(this.T.delayTime,b,e,g)}}};self.Je=class extends d{constructor(a,b,e,g){super(a);this.P="convolution";this.g=[e,g];this.ge=this.fe="";this.m=this.s();this.c=this.s();this.c.gain.value=g;this.b=this.s();this.b.gain.value=
1-g;this.ib=this.a.createConvolver();this.ib.normalize=e;this.ib.buffer=b;this.m.connect(this.ib);this.m.connect(this.b);this.ib.connect(this.c)}f(){this.m.disconnect();this.ib.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.m}Y(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.o(this.c.gain,b,e,g),this.o(this.b.gain,1-b,e,g)}}Pg(a,b){this.fe=a;this.ge=b}Xa(){const a=
super.Xa();a.bufferOriginalUrl=this.fe;a.bufferUrl="";a.bufferType=this.ge;return a}};self.Ne=class extends d{constructor(a,b,e,g,m,q){super(a);this.P="flanger";this.g=[b,e,g,m,q];this.m=this.s();this.b=this.s();this.b.gain.value=1-q/2;this.c=this.s();this.c.gain.value=q/2;this.lb=this.s();this.lb.gain.value=m;this.T=this.a.createDelay(b+e);this.T.delayTime.value=b;this.v=this.a.createOscillator();this.v.frequency.value=g;this.H=this.s();this.H.gain.value=e;this.m.connect(this.T);this.m.connect(this.b);
this.T.connect(this.c);this.T.connect(this.lb);this.lb.connect(this.T);this.v.connect(this.H);this.H.connect(this.T.delayTime);this.v.start(0)}f(){this.v.stop(0);this.m.disconnect();this.T.disconnect();this.v.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();this.lb.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.m}Y(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.o(this.c.gain,
b/2,e,g);this.o(this.b.gain,1-b/2,e,g);break;case 6:this.g[1]=b/1E3;this.o(this.H.gain,b/1E3,e,g);break;case 7:this.g[2]=b;this.o(this.v.frequency,b,e,g);break;case 8:this.g[3]=b/100,this.o(this.lb.gain,b/100,e,g)}}};self.Pe=class extends d{constructor(a,b,e,g,m,q,u){super(a);this.P="phaser";this.g=[b,e,g,m,q,u];this.m=this.s();this.b=this.s();this.b.gain.value=1-u/2;this.c=this.s();this.c.gain.value=u/2;this.A=this.a.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
e;this.A.Q.value=g;this.v=this.a.createOscillator();this.v.frequency.value=q;this.H=this.s();this.H.gain.value=m;this.m.connect(this.A);this.m.connect(this.b);this.A.connect(this.c);this.v.connect(this.H);this.H.connect(this.A.frequency);this.v.start(0)}f(){this.v.stop(0);this.m.disconnect();this.A.disconnect();this.v.disconnect();this.H.disconnect();this.b.disconnect();this.c.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.m}Y(a,
b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.o(this.c.gain,b/2,e,g);this.o(this.b.gain,1-b/2,e,g);break;case 1:this.g[0]=b;this.o(this.A.frequency,b,e,g);break;case 2:this.g[1]=b;this.o(this.A.detune,b,e,g);break;case 3:this.g[2]=b;this.o(this.A.Q,b,e,g);break;case 6:this.g[3]=b;this.o(this.H.gain,b,e,g);break;case 7:this.g[4]=b,this.o(this.v.frequency,b,e,g)}}};self.Oe=class extends d{constructor(a,b){super(a);this.P="gain";this.g=[b];this.i=this.s();this.i.gain.value=
b}f(){this.i.disconnect();super.f()}R(a){this.i.disconnect();this.i.connect(a)}O(){return this.i}Y(a,b,e,g){const m=self.ha.Ed;switch(a){case 4:this.g[0]=m(b),this.o(this.i.gain,m(b),e,g)}}};self.Re=class extends d{constructor(a,b,e){super(a);this.P="tremolo";this.g=[b,e];this.i=this.s();this.i.gain.value=1-e/2;this.v=this.a.createOscillator();this.v.frequency.value=b;this.H=this.s();this.H.gain.value=e/2;this.v.connect(this.H);this.H.connect(this.i.gain);this.v.start(0)}f(){this.v.stop(0);this.v.disconnect();
this.H.disconnect();this.i.disconnect();super.f()}R(a){this.i.disconnect();this.i.connect(a)}O(){return this.i}Y(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.o(this.i.gain,1-b/2,e,g);this.o(this.H.gain,b/2,e,g);break;case 7:this.g[0]=b,this.o(this.v.frequency,b,e,g)}}};self.Qe=class extends d{constructor(a,b,e){super(a);this.P="ringmod";this.g=[b,e];this.m=this.s();this.c=this.s();this.c.gain.value=e;this.b=this.s();this.b.gain.value=1-e;this.zb=this.s();this.zb.gain.value=
0;this.v=this.a.createOscillator();this.v.frequency.value=b;this.v.connect(this.zb.gain);this.v.start(0);this.m.connect(this.zb);this.m.connect(this.b);this.zb.connect(this.c)}f(){this.v.stop(0);this.v.disconnect();this.zb.disconnect();this.m.disconnect();this.c.disconnect();this.b.disconnect();super.f()}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();this.b.connect(a)}O(){return this.m}Y(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.o(this.c.gain,b,e,g);
this.o(this.b.gain,1-b,e,g);break;case 7:this.g[0]=b,this.o(this.v.frequency,b,e,g)}}};self.Le=class extends d{constructor(a,b,e,g,m,q){super(a);this.P="distortion";this.g=[b,e,g,m,q];this.m=this.s();this.nc=this.s();this.mc=this.s();this.Qg(g,m);this.c=this.s();this.c.gain.value=q;this.b=this.s();this.b.gain.value=1-q;this.sc=this.a.createWaveShaper();this.ed=new Float32Array(65536);this.Lf(b,e);this.sc.curve=this.ed;this.m.connect(this.nc);this.m.connect(this.b);this.nc.connect(this.sc);this.sc.connect(this.mc);
this.mc.connect(this.c)}f(){this.m.disconnect();this.nc.disconnect();this.sc.disconnect();this.mc.disconnect();this.c.disconnect();this.b.disconnect();super.f()}Qg(a,b){.01>a&&(a=.01);this.nc.gain.value=a;this.mc.gain.value=Math.pow(1/a,.6)*b}Lf(a,b){for(let e=0;32768>e;++e){let g=e/32768;g=this.eh(g,a,b);this.ed[32768+e]=g;this.ed[32768-e-1]=-g}}eh(a,b,e){e=1.05*e*b-b;const g=0>a?-a:a;return(g<b?g:b+e*self.ha.vh(g-b,1/e))*(0>a?-1:1)}R(a){this.c.disconnect();this.c.connect(a);this.b.disconnect();
this.b.connect(a)}O(){return this.m}Y(a,b,e,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.o(this.c.gain,b,e,g),this.o(this.b.gain,1-b,e,g)}}};self.Ie=class extends d{constructor(a,b,e,g,m,q){super(a);this.P="compressor";this.g=[b,e,g,m,q];this.i=this.a.createDynamicsCompressor();this.i.threshold.value=b;this.i.knee.value=e;this.i.ratio.value=g;this.i.attack.value=m;this.i.release.value=q}f(){this.i.disconnect();super.f()}R(a){this.i.disconnect();this.i.connect(a)}O(){return this.i}Y(){}};
self.He=class extends d{constructor(a,b,e){super(a);this.P="analyser";this.g=[b,e];this.i=this.a.createAnalyser();this.i.fftSize=b;this.i.smoothingTimeConstant=e;this.me=new Float32Array(this.i.frequencyBinCount);this.Ae=new Uint8Array(b);this.ye=this.Qa=0;this.l.uf(this)}f(){this.l.Jg(this);this.i.disconnect();super.f()}Ba(){this.i.getFloatFrequencyData(this.me);this.i.getByteTimeDomainData(this.Ae);const a=this.i.fftSize;let b=this.Qa=0;for(var e=0;e<a;++e){let g=(this.Ae[e]-128)/128;0>g&&(g=-g);
this.Qa<g&&(this.Qa=g);b+=g*g}e=self.ha.hf;this.Qa=e(this.Qa);this.ye=e(Math.sqrt(b/a))}R(a){this.i.disconnect();this.i.connect(a)}O(){return this.i}Y(){}af(){return{tag:this.aa,index:this.pe,peak:this.Qa,rms:this.ye,binCount:this.i.frequencyBinCount,freqBins:this.me}}}};
